import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { spawnSync } from 'node:child_process';
import { readThemeMaps, resolveTokenColor } from '../scripts/resolve-tokens.js';
import { buildThemeData, renderThemeData, GENERATOR_FILES, THEME_DATA_FILE } from '../scripts/build-create-theme.js';
import { TARGET_LIGHTNESS, measureLightness } from '../tokens/chromatic-scales.js';

/**
 * The theme generator, tested as it ships: built into dist/create-theme/ and
 * imported, or run, from there under plain Node. Nothing here reads the
 * generator's source directory, so a file the build forgot to copy fails.
 *
 * Part of `npm run test:themes`, not vitest: the published artefact only
 * exists after a build, and this file makes its own.
 */

const projectRoot = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const distDir = path.join(projectRoot, 'dist', 'create-theme');
const cli = path.join(distDir, 'cli.js');

const built = spawnSync(process.execPath, ['scripts/build-create-theme.js'], { cwd: projectRoot, encoding: 'utf8' });
assert.equal(built.status, 0, `build-create-theme failed:\n${built.stdout}\n${built.stderr}`);

const { createTheme, default: defaultExport, RAMP_STEPS, BASE_STEPS } = await import(
  pathToFileURL(path.join(distDir, 'index.js')).href
);

/** The default theme, straight from the stylesheet (not from the generator's copy). */
const defaults = readThemeMaps(fs.readFileSync(path.join(projectRoot, 'src', 'app.css'), 'utf8'));

/** What a page computes with `tokens` imported after the theme files. */
function themed(tokens) {
  return {
    light: { ...defaults.light, ...tokens },
    dark: { ...defaults.light, ...defaults.darkOnly, ...tokens },
  };
}

const run = (...args) => spawnSync(process.execPath, [cli, ...args], { encoding: 'utf8' });
const contrastWarnings = (result) => result.warnings.filter((w) => w.type === 'contrast');

const BRANDS = ['#0026EA', '#C17B00'];

test('the build puts every generator file in dist, with fresh theme data', () => {
  for (const file of [...GENERATOR_FILES, THEME_DATA_FILE]) {
    assert.ok(fs.existsSync(path.join(distDir, file)), `missing dist/create-theme/${file}`);
  }
  // The generator checks an app's brand against this copy of the default
  // theme. It must be exactly what src/app.css and the pair list say today.
  assert.equal(fs.readFileSync(path.join(distDir, THEME_DATA_FILE), 'utf8'), renderThemeData(buildThemeData()));
  const data = buildThemeData();
  assert.ok(data.pairs.length >= 58, 'the contrast pair list shrank');
  assert.ok(data.pairs.some((pair) => pair.fg === '--color-on-brand'));
  assert.ok(fs.readFileSync(cli, 'utf8').startsWith('#!/usr/bin/env node'));
  assert.ok(fs.statSync(cli).mode & 0o111, 'cli.js is not executable');
});

test('createTheme returns css, tokens, warnings and closest', () => {
  const result = createTheme({ brand: '#0026EA' });
  assert.equal(defaultExport, createTheme);
  assert.deepEqual(Object.keys(result).sort(), ['closest', 'css', 'tokens', 'warnings']);
  assert.equal(typeof result.css, 'string');
  assert.ok(Array.isArray(result.warnings));

  assert.deepEqual(Object.keys(result.tokens), [
    ...RAMP_STEPS.map((step) => `--zabi-brand-${step}`),
    '--zabi-on-brand',
    '--zabi-on-brand-dark',
  ]);
  for (const step of RAMP_STEPS) assert.match(result.tokens[`--zabi-brand-${step}`], /^#[0-9a-f]{6}$/);

  // The css is the tokens, on :root, under a header comment and nothing else.
  const body = /^\/\*[\s\S]*?\*\/\n:root \{\n([\s\S]*)\n\}\n$/.exec(result.css);
  assert.ok(body, 'css is not a header comment followed by one :root rule');
  assert.deepEqual(
    body[1].split('\n'),
    Object.entries(result.tokens).map(([name, value]) => `  ${name}: ${value};`),
  );
  // No accent or neutral was asked for, so the library's own stay in force.
  assert.ok(!result.css.includes('--zabi-accent-'));
  assert.ok(!result.css.includes('--zabi-base-'));
});

test('the same input gives the same bytes, and the header names the inputs', () => {
  const options = { brand: '#0026EA', accent: '#ff3366', neutral: '#78716c' };
  const first = createTheme(options);
  assert.equal(createTheme({ ...options }).css, first.css);
  assert.equal(createTheme({ brand: '0026ea', accent: 'FF3366', neutral: '#78716C' }).css, first.css);

  assert.match(first.css, /Generated by zabi-theme/);
  assert.match(first.css, /brand {4}#0026ea {2}closest step 800/);
  assert.match(first.css, /accent {3}#ff3366 {2}closest step \d+/);
  assert.match(first.css, /neutral {2}#78716c {2}closest step \d+/);
  assert.match(first.css, /the exact hex may not appear below/);
  // Nothing that changes from run to run.
  assert.doesNotMatch(first.css, /\b20\d\d-\d\d-\d\d\b|\d\d:\d\d/);
});

for (const brand of BRANDS) {
  test(`${brand}: the ramp is on the library's lightness curve and every guarded pair passes`, () => {
    const result = createTheme({ brand });
    assert.deepEqual(contrastWarnings(result), []);
    assert.match(result.css, /Contrast: all \d+ role pairs pass WCAG AA in light and dark\./);
    for (const step of RAMP_STEPS) {
      const lightness = measureLightness(result.tokens[`--zabi-brand-${step}`]);
      assert.ok(
        Math.abs(lightness - TARGET_LIGHTNESS[step]) <= 1.5,
        `${brand} step ${step} is L* ${lightness}, the curve says ${TARGET_LIGHTNESS[step]}`,
      );
    }
  });

  test(`${brand}: imported after the theme, it restyles light and dark`, () => {
    const { tokens } = createTheme({ brand });
    const { light, dark } = themed(tokens);
    const step = (n) => tokens[`--zabi-brand-${n}`];
    assert.equal(resolveTokenColor(light, '--color-action-primary'), step(600));
    assert.equal(resolveTokenColor(light, '--color-action-primary-hover'), step(700));
    assert.equal(resolveTokenColor(light, '--color-focus-ring'), step(600));
    assert.equal(resolveTokenColor(light, '--color-link'), step(700));
    assert.equal(resolveTokenColor(light, '--color-action-primary-text'), '#ffffff');
    assert.equal(resolveTokenColor(dark, '--color-action-primary'), step(400));
    assert.equal(resolveTokenColor(dark, '--color-action-primary-hover'), step(300));
    // The same step as the dark primary fill: brand-500 was under 3:1 on the overlay.
    assert.equal(resolveTokenColor(dark, '--color-focus-ring'), step(400));
    assert.equal(resolveTokenColor(dark, '--color-link'), step(300));
    assert.equal(resolveTokenColor(dark, '--color-action-primary-text'), step(950));
  });
}

test('the input colour supplies hue and chroma and is reported against its closest step', () => {
  // #C17B00 sits on the curve at step 500, so it comes back exactly.
  const amber = createTheme({ brand: '#C17B00' });
  assert.deepEqual(amber.closest.brand, { step: 500, hex: '#c17b00', deltaE: 0, exact: true });
  assert.equal(amber.tokens['--zabi-brand-500'], '#c17b00');

  // #0026EA is darker than step 600: it is not pinned there, and the header says where it went.
  const blue = createTheme({ brand: '#0026EA' });
  assert.equal(blue.closest.brand.step, 800);
  assert.equal(blue.closest.brand.exact, false);
  assert.ok(blue.closest.brand.deltaE > 0 && blue.closest.brand.deltaE < 10);
  assert.notEqual(blue.tokens['--zabi-brand-600'], '#0026ea');
});

test('the "on" colours are chosen so the label passes on the fill', () => {
  // Default recipe: fill at 600 carries white; the mirrored dark fill carries the ramp's dark end.
  const plain = createTheme({ brand: '#C17B00', accent: '#ff3366' });
  assert.equal(plain.tokens['--zabi-on-brand'], '#ffffff');
  assert.equal(plain.tokens['--zabi-on-brand-dark'], 'var(--zabi-brand-950)');
  assert.equal(plain.tokens['--zabi-on-accent'], '#ffffff');
  assert.equal(plain.tokens['--zabi-on-accent-dark'], 'var(--zabi-accent-950)');

  // A brand that wants its bright step as the button: white would be about 2:1.
  const bright = createTheme({
    brand: '#FFC400',
    overrides: {
      '--color-action-primary': 'var(--zabi-brand-300)',
      '--color-action-primary-hover': 'var(--zabi-brand-400)',
      '--color-action-primary-active': 'var(--zabi-brand-500)',
    },
  });
  assert.equal(bright.tokens['--zabi-on-brand'], 'var(--zabi-brand-950)');
  assert.equal(bright.tokens['--zabi-on-brand-dark'], 'var(--zabi-brand-950)');
  assert.ok(!bright.warnings.some((w) => w.type === 'contrast' && w.foreground.token === '--color-action-primary-text'));
  assert.ok(!bright.warnings.some((w) => w.type === 'contrast' && w.foreground.token === '--color-on-brand'));
  // Overrides are written into the file, after the ramps.
  assert.match(bright.css, /--color-action-primary: var\(--zabi-brand-300\);\n/);
});

test('a role pair below WCAG AA comes back as a structured warning, per mode', () => {
  const result = createTheme({ brand: '#0026EA', overrides: { '--color-link': 'var(--zabi-brand-400)' } });
  const warnings = contrastWarnings(result);
  assert.deepEqual(warnings.map((w) => `${w.mode} ${w.pair}`), ['light link on page', 'light link on card']);
  const [onPage] = warnings;
  assert.equal(onPage.required, 4.5);
  assert.ok(onPage.ratio < 4.5 && onPage.ratio > 1);
  assert.deepEqual(onPage.foreground, { token: '--color-link', value: result.tokens['--zabi-brand-400'] });
  assert.deepEqual(onPage.background, { token: '--color-surface-base', value: '#ececee' });
  assert.match(onPage.message, /light · link on page: #[0-9a-f]{6} on #ececee is [\d.]+:1, needs 4\.5:1/);
  // The failure is in the file too, so it is not lost when stderr is.
  assert.match(result.css, /Contrast: 2 of \d+ role pairs are below WCAG AA:/);

  // 3:1 pairs are checked as well: a focus ring too pale for the page.
  const ring = createTheme({ brand: '#0026EA', overrides: { '--color-focus': 'var(--zabi-brand-300)' } });
  assert.ok(contrastWarnings(ring).some((w) => w.required === 3 && w.mode === 'light' && /focus ring/.test(w.pair)));
});

test('grey, near-white and near-black brands warn instead of crashing', () => {
  for (const brand of ['#808080', '#ffffff', '#000000', '#fefce8', '#050505']) {
    const result = createTheme({ brand });
    const notes = result.warnings.filter((w) => w.type === 'input');
    assert.equal(notes.length, 1, `${brand}: expected one input warning`);
    assert.equal(notes[0].option, 'brand');
    assert.ok(notes[0].message.includes(brand));
    for (const step of RAMP_STEPS) assert.match(result.tokens[`--zabi-brand-${step}`], /^#[0-9a-f]{6}$/);
    // Still a usable ramp on the curve, so the pairs hold.
    assert.deepEqual(contrastWarnings(result), []);
  }
  assert.match(createTheme({ brand: '#808080' }).warnings[0].message, /almost no colour/);
  assert.match(createTheme({ brand: '#fefce8' }).warnings[0].message, /nearly white/);
  // A colour too bright for the curve is reported against its nearest step.
  assert.match(createTheme({ brand: '#FFE600' }).warnings[0].message, /is not in the ramp built from it: the nearest step is \d+/);
});

test('invalid input is a TypeError with a message that says what to pass', () => {
  assert.throws(() => createTheme(), TypeError);
  assert.throws(() => createTheme({}), /brand is required/);
  assert.throws(() => createTheme({ brand: 'blue' }), /brand must be a hex colour such as "#0026EA" or "#06e" \(got "blue"\)/);
  assert.throws(() => createTheme({ brand: '#12345' }), TypeError);
  assert.throws(() => createTheme({ brand: 123 }), /got 123/);
  assert.throws(() => createTheme({ brand: '#0026EA', accent: 'rgb(0,0,0)' }), /accent must be a hex colour/);
  assert.throws(() => createTheme({ brand: '#0026EA', neutral: '' }), /neutral must be a hex colour/);
  assert.throws(() => createTheme({ brand: '#0026EA', overrides: { 'color-link': 'red' } }), /overrides must map custom property names/);
});

test('neutral produces all 21 steps on the base scale\'s own lightness, tinted toward the hue', () => {
  const result = createTheme({ brand: '#0026EA', neutral: '#78716c' });
  assert.equal(BASE_STEPS.length, 21);
  for (const half of [75, 150, 250, 350, 450, 550, 650, 750, 850, 925]) assert.ok(BASE_STEPS.includes(half));

  for (const step of BASE_STEPS) {
    const hex = result.tokens[`--zabi-base-${step}`];
    assert.match(hex, /^#[0-9a-f]{6}$/, `--zabi-base-${step}`);
    const expected = measureLightness(defaults.light[`--zabi-base-${step}`]);
    assert.ok(Math.abs(measureLightness(hex) - expected) <= 1, `base-${step} is L* ${measureLightness(hex)}, the base scale has ${expected}`);
    // Warm: red at or above blue, where the default zinc greys lean blue.
    const [r, , b] = [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16));
    assert.ok(r >= b, `base-${step} ${hex} is not tinted warm`);
  }
  assert.notEqual(result.tokens['--zabi-base-500'], defaults.light['--zabi-base-500']);
  assert.deepEqual(contrastWarnings(result), []);

  // The whole neutral system follows, dark surfaces included.
  const { light, dark } = themed(result.tokens);
  assert.equal(resolveTokenColor(light, '--color-headline'), result.tokens['--zabi-base-900']);
  assert.equal(resolveTokenColor(dark, '--color-surface-base'), result.tokens['--zabi-base-900']);
  assert.notEqual(resolveTokenColor(dark, '--color-surface-raised'), '#262629');

  // A saturated colour as the neutral is only a hue: it stays a grey, and says so.
  const loud = createTheme({ brand: '#0026EA', neutral: '#C17B00' });
  assert.match(loud.warnings.find((w) => w.option === 'neutral').message, /only its hue is used/);
  const [r, g, b] = [1, 3, 5].map((i) => parseInt(loud.tokens['--zabi-base-500'].slice(i, i + 2), 16));
  assert.ok(Math.max(r, g, b) - Math.min(r, g, b) < 40, 'a neutral step came out saturated');
  assert.deepEqual(contrastWarnings(loud), []);
});

test('accent builds its own ramp and labels, and every pair still passes for both brands', () => {
  for (const brand of BRANDS) {
    const result = createTheme({ brand, accent: '#ff3366', neutral: '#78716c' });
    for (const step of RAMP_STEPS) assert.match(result.tokens[`--zabi-accent-${step}`], /^#[0-9a-f]{6}$/);
    assert.deepEqual(contrastWarnings(result), []);
    const { light, dark } = themed(result.tokens);
    assert.equal(resolveTokenColor(light, '--color-accent'), result.tokens['--zabi-accent-600']);
    assert.equal(resolveTokenColor(dark, '--color-accent'), result.tokens['--zabi-accent-400']);
    assert.equal(resolveTokenColor(dark, '--color-on-accent'), result.tokens['--zabi-accent-950']);
  }
});

test('the bin runs from dist: css on stdout, summary on stderr', () => {
  for (const brand of BRANDS) {
    const result = run('--brand', brand);
    assert.equal(result.status, 0, result.stderr);
    assert.equal(result.stdout, createTheme({ brand }).css);
    assert.match(result.stderr, /every role pair passes WCAG AA in light and dark\./);
    assert.doesNotMatch(result.stderr, /warning:/);
  }
  const full = run('--brand=#0026EA', '--accent', '#ff3366', '--neutral', '#78716c', '--strict');
  assert.equal(full.status, 0, full.stderr);
  assert.equal(full.stdout, createTheme({ brand: '#0026EA', accent: '#ff3366', neutral: '#78716c' }).css);

  const help = run('--help');
  assert.equal(help.status, 0);
  assert.match(help.stdout, /--brand <hex>/);
  assert.match(help.stdout, /--strict/);
});

test('the bin writes --out and keeps stdout empty', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'zabi-theme-'));
  try {
    const target = path.join(dir, 'nested', 'brand.generated.css');
    const result = run('--brand', '#C17B00', '--out', target);
    assert.equal(result.status, 0, result.stderr);
    assert.equal(result.stdout, '');
    assert.equal(fs.readFileSync(target, 'utf8'), createTheme({ brand: '#C17B00' }).css);
    assert.match(result.stderr, /wrote .*brand\.generated\.css \(brand closest to step 500\)/);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test('the bin refuses bad input with a clear message and exit 2', () => {
  const cases = [
    [[], /--brand is required/],
    [['--brand'], /--brand needs a value/],
    [['--brand', 'blue'], /brand must be a hex colour such as "#0026EA" or "#06e" \(got "blue"\)/],
    [['--brand', '#0026EA', '--accent', '#zzz'], /accent must be a hex colour/],
    [['--brand', '#0026EA', '--colour', 'x'], /unknown option "--colour"/],
    [['--brand', '#0026EA', 'stray'], /unexpected argument "stray"/],
    [['--brand', '#0026EA', '--set', 'nonsense'], /--set needs <token>=<value>/],
  ];
  for (const [args, message] of cases) {
    const result = run(...args);
    assert.equal(result.status, 2, `${args.join(' ')} exited ${result.status}`);
    assert.match(result.stderr, message);
    assert.equal(result.stdout, '', `${args.join(' ')} printed css`);
  }
});

test('the bin warns on stderr, and --strict turns a failed pair into exit 1', () => {
  const args = ['--brand', '#0026EA', '--set', '--color-link=var(--zabi-brand-400)'];
  const lenient = run(...args);
  assert.equal(lenient.status, 0);
  assert.match(lenient.stderr, /warning: light · link on page: .* needs 4\.5:1/);
  assert.match(lenient.stderr, /2 role pairs below WCAG AA\./);
  assert.match(lenient.stdout, /--color-link: var\(--zabi-brand-400\);/);

  const strict = run(...args, '--strict');
  assert.equal(strict.status, 1);
  assert.equal(strict.stdout, lenient.stdout);

  // An input note is not a failed pair: --strict lets a grey brand through.
  const grey = run('--brand', '#808080', '--strict');
  assert.equal(grey.status, 0);
  assert.match(grey.stderr, /warning: brand #808080 has almost no colour/);
});
