import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { spawnSync } from 'node:child_process';
import postcss from 'postcss';
import { readThemeMaps, resolveTokenColor, resolveTokenValue } from '../scripts/resolve-tokens.js';
import { buildThemeData, renderThemeData, GENERATOR_FILES, THEME_DATA_FILE } from '../scripts/build-create-theme.js';
import { TARGET_LIGHTNESS, measureLightness } from '../tokens/chromatic-scales.js';

/**
 * The theme generator, tested as it ships: built into dist/create-theme/ and
 * imported, or run, from there under plain Node. Nothing here reads the
 * generator's source directory, so a file the build forgot to copy fails.
 *
 * Part of `npm run test:themes`, not vitest: the published artefact only
 * exists after a build, and this file makes its own.
 */

const projectRoot = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const distDir = path.join(projectRoot, 'dist', 'create-theme');
const cli = path.join(distDir, 'cli.js');

const built = spawnSync(process.execPath, ['scripts/build-create-theme.js'], { cwd: projectRoot, encoding: 'utf8' });
assert.equal(built.status, 0, `build-create-theme failed:\n${built.stdout}\n${built.stderr}`);

const { createTheme, default: defaultExport, RAMP_STEPS, BASE_STEPS } = await import(
  pathToFileURL(path.join(distDir, 'index.js')).href
);

/** The default theme, straight from the stylesheet (not from the generator's copy). */
const defaults = readThemeMaps(fs.readFileSync(path.join(projectRoot, 'src', 'app.css'), 'utf8'));

/** What a page computes with `tokens` imported after the theme files. */
function themed(tokens) {
  return {
    light: { ...defaults.light, ...tokens },
    dark: { ...defaults.light, ...defaults.darkOnly, ...tokens },
  };
}

const run = (...args) => spawnSync(process.execPath, [cli, ...args], { encoding: 'utf8' });
const contrastWarnings = (result) => result.warnings.filter((w) => w.type === 'contrast');

const BRANDS = ['#0026EA', '#C17B00'];

test('the build puts every generator file in dist, with fresh theme data', () => {
  for (const file of [...GENERATOR_FILES, THEME_DATA_FILE]) {
    assert.ok(fs.existsSync(path.join(distDir, file)), `missing dist/create-theme/${file}`);
  }
  // The generator checks an app's brand against this copy of the default
  // theme. It must be exactly what src/app.css and the pair list say today.
  assert.equal(fs.readFileSync(path.join(distDir, THEME_DATA_FILE), 'utf8'), renderThemeData(buildThemeData()));
  const data = buildThemeData();
  assert.ok(data.pairs.length >= 58, 'the contrast pair list shrank');
  assert.ok(data.pairs.some((pair) => pair.fg === '--color-on-brand'));
  assert.ok(fs.readFileSync(cli, 'utf8').startsWith('#!/usr/bin/env node'));
  assert.ok(fs.statSync(cli).mode & 0o111, 'cli.js is not executable');
});

test('createTheme returns css, tokens, warnings and closest', () => {
  const result = createTheme({ brand: '#0026EA' });
  assert.equal(defaultExport, createTheme);
  assert.deepEqual(Object.keys(result).sort(), ['closest', 'css', 'tokens', 'warnings']);
  assert.equal(typeof result.css, 'string');
  assert.ok(Array.isArray(result.warnings));

  assert.deepEqual(Object.keys(result.tokens), [
    ...RAMP_STEPS.map((step) => `--zabi-brand-${step}`),
    '--zabi-on-brand',
    '--zabi-on-brand-dark',
  ]);
  for (const step of RAMP_STEPS) assert.match(result.tokens[`--zabi-brand-${step}`], /^#[0-9a-f]{6}$/);

  // The css is the tokens, on :root, under a header comment and nothing else.
  const body = /^\/\*[\s\S]*?\*\/\n:root \{\n([\s\S]*)\n\}\n$/.exec(result.css);
  assert.ok(body, 'css is not a header comment followed by one :root rule');
  assert.deepEqual(
    body[1].split('\n'),
    Object.entries(result.tokens).map(([name, value]) => `  ${name}: ${value};`),
  );
  // No accent or neutral was asked for, so the library's own stay in force.
  assert.ok(!result.css.includes('--zabi-accent-'));
  assert.ok(!result.css.includes('--zabi-base-'));
});

test('the same input gives the same bytes, and the header names the inputs', () => {
  const options = { brand: '#0026EA', accent: '#ff3366', neutral: '#78716c' };
  const first = createTheme(options);
  assert.equal(createTheme({ ...options }).css, first.css);
  assert.equal(createTheme({ brand: '0026ea', accent: 'FF3366', neutral: '#78716C' }).css, first.css);

  assert.match(first.css, /Generated by zabi-theme/);
  assert.match(first.css, /brand {4}#0026ea {2}closest step 800/);
  assert.match(first.css, /accent {3}#ff3366 {2}closest step \d+/);
  assert.match(first.css, /neutral {2}#78716c {2}closest step \d+/);
  assert.match(first.css, /the exact hex may not appear below/);
  // Nothing that changes from run to run.
  assert.doesNotMatch(first.css, /\b20\d\d-\d\d-\d\d\b|\d\d:\d\d/);
});

for (const brand of BRANDS) {
  test(`${brand}: the ramp is on the library's lightness curve and every guarded pair passes`, () => {
    const result = createTheme({ brand });
    assert.deepEqual(contrastWarnings(result), []);
    assert.match(result.css, /Contrast: all \d+ role pairs pass WCAG AA in light and dark\./);
    for (const step of RAMP_STEPS) {
      const lightness = measureLightness(result.tokens[`--zabi-brand-${step}`]);
      assert.ok(
        Math.abs(lightness - TARGET_LIGHTNESS[step]) <= 1.5,
        `${brand} step ${step} is L* ${lightness}, the curve says ${TARGET_LIGHTNESS[step]}`,
      );
    }
  });

  test(`${brand}: imported after the theme, it restyles light and dark`, () => {
    const { tokens } = createTheme({ brand });
    const { light, dark } = themed(tokens);
    const step = (n) => tokens[`--zabi-brand-${n}`];
    assert.equal(resolveTokenColor(light, '--color-action-primary'), step(600));
    assert.equal(resolveTokenColor(light, '--color-action-primary-hover'), step(700));
    assert.equal(resolveTokenColor(light, '--color-focus-ring'), step(600));
    assert.equal(resolveTokenColor(light, '--color-link'), step(700));
    assert.equal(resolveTokenColor(light, '--color-action-primary-text'), '#ffffff');
    // The primary keeps its hue in dark (Z-043): the same steps as light, a white label.
    assert.equal(resolveTokenColor(dark, '--color-action-primary'), step(600));
    assert.equal(resolveTokenColor(dark, '--color-action-primary-hover'), step(700));
    assert.equal(resolveTokenColor(dark, '--color-action-primary-active'), step(800));
    // The ring and the link stay on the light mirrored steps: brand-500 was under 3:1 on the overlay.
    assert.equal(resolveTokenColor(dark, '--color-focus-ring'), step(400));
    assert.equal(resolveTokenColor(dark, '--color-link'), step(300));
    assert.equal(resolveTokenColor(dark, '--color-action-primary-text'), '#ffffff');
  });
}

test('the input colour supplies hue and chroma and is reported against its closest step', () => {
  // #C17B00 sits on the curve at step 500, so it comes back exactly.
  const amber = createTheme({ brand: '#C17B00' });
  assert.deepEqual(amber.closest.brand, { step: 500, hex: '#c17b00', deltaE: 0, exact: true });
  assert.equal(amber.tokens['--zabi-brand-500'], '#c17b00');

  // #0026EA is darker than step 600: it is not pinned there, and the header says where it went.
  const blue = createTheme({ brand: '#0026EA' });
  assert.equal(blue.closest.brand.step, 800);
  assert.equal(blue.closest.brand.exact, false);
  assert.ok(blue.closest.brand.deltaE > 0 && blue.closest.brand.deltaE < 10);
  assert.notEqual(blue.tokens['--zabi-brand-600'], '#0026ea');
});

test('the "on" colours are chosen so the label passes on the fill', () => {
  // Default recipe: fill at 600 carries white, in light and in dark (the same fill).
  const plain = createTheme({ brand: '#C17B00', accent: '#ff3366' });
  assert.equal(plain.tokens['--zabi-on-brand'], '#ffffff');
  assert.equal(plain.tokens['--zabi-on-brand-dark'], '#ffffff');
  assert.equal(plain.tokens['--zabi-on-accent'], '#ffffff');
  assert.equal(plain.tokens['--zabi-on-accent-dark'], 'var(--zabi-accent-950)');

  // A brand that wants its bright step as the button: white would be about 2:1.
  const bright = createTheme({
    brand: '#FFC400',
    overrides: {
      '--color-action-primary': 'var(--zabi-brand-300)',
      '--color-action-primary-hover': 'var(--zabi-brand-400)',
      '--color-action-primary-active': 'var(--zabi-brand-500)',
    },
  });
  assert.equal(bright.tokens['--zabi-on-brand'], 'var(--zabi-brand-950)');
  assert.equal(bright.tokens['--zabi-on-brand-dark'], 'var(--zabi-brand-950)');
  assert.ok(!bright.warnings.some((w) => w.type === 'contrast' && w.foreground.token === '--color-action-primary-text'));
  assert.ok(!bright.warnings.some((w) => w.type === 'contrast' && w.foreground.token === '--color-on-brand'));
  // Overrides are written into the file, after the ramps.
  assert.match(bright.css, /--color-action-primary: var\(--zabi-brand-300\);\n/);
});

test('a role pair below WCAG AA comes back as a structured warning, per mode', () => {
  const result = createTheme({ brand: '#0026EA', overrides: { '--color-link': 'var(--zabi-brand-400)' } });
  const warnings = contrastWarnings(result);
  // The link colour is also the icon of a toggled-on ghost IconButton, held
  // down, the label of a selected pill Tab, the text of a subtle brand Badge and
  // the active label of a BottomTabBar (--color-nav-menu-item-active).
  assert.deepEqual(warnings.map((w) => `${w.mode} ${w.pair}`), [
    'light badge subtle · brand',
    'light link on page',
    'light link on card',
    'light icon on a held toggled-on fill',
    'light label on a selected pill tab',
    'light active tab label on the tab pill',
  ]);
  const onPage = warnings.find((w) => w.pair === 'link on page');
  assert.equal(onPage.required, 4.5);
  assert.ok(onPage.ratio < 4.5 && onPage.ratio > 1);
  assert.deepEqual(onPage.foreground, { token: '--color-link', value: result.tokens['--zabi-brand-400'] });
  assert.deepEqual(onPage.background, { token: '--color-surface-base', value: '#fafafa' });
  assert.match(onPage.message, /light · link on page: #[0-9a-f]{6} on #fafafa is [\d.]+:1, needs 4\.5:1/);
  // The failure is in the file too, so it is not lost when stderr is.
  assert.match(result.css, /Contrast: 6 of \d+ role pairs are below WCAG AA:/);

  // 3:1 pairs are checked as well: a focus ring too pale for the page.
  const ring = createTheme({ brand: '#0026EA', overrides: { '--color-focus': 'var(--zabi-brand-300)' } });
  assert.ok(contrastWarnings(ring).some((w) => w.required === 3 && w.mode === 'light' && /focus ring/.test(w.pair)));
});

test('grey, near-white and near-black brands warn instead of crashing', () => {
  for (const brand of ['#808080', '#ffffff', '#000000', '#fefce8', '#050505']) {
    const result = createTheme({ brand });
    const notes = result.warnings.filter((w) => w.type === 'input');
    assert.equal(notes.length, 1, `${brand}: expected one input warning`);
    assert.equal(notes[0].option, 'brand');
    assert.ok(notes[0].message.includes(brand));
    for (const step of RAMP_STEPS) assert.match(result.tokens[`--zabi-brand-${step}`], /^#[0-9a-f]{6}$/);
    // Still a usable ramp on the curve, so the pairs hold.
    assert.deepEqual(contrastWarnings(result), []);
  }
  assert.match(createTheme({ brand: '#808080' }).warnings[0].message, /almost no colour/);
  assert.match(createTheme({ brand: '#fefce8' }).warnings[0].message, /nearly white/);
  // A colour too bright for the curve is reported against its nearest step.
  assert.match(createTheme({ brand: '#FFE600' }).warnings[0].message, /is not in the ramp built from it: the nearest step is \d+/);
});

test('invalid input is a TypeError with a message that says what to pass', () => {
  assert.throws(() => createTheme(), TypeError);
  assert.throws(() => createTheme({}), /brand is required/);
  assert.throws(() => createTheme({ brand: 'blue' }), /brand must be a hex colour such as "#0026EA" or "#06e" \(got "blue"\)/);
  assert.throws(() => createTheme({ brand: '#12345' }), TypeError);
  assert.throws(() => createTheme({ brand: 123 }), /got 123/);
  assert.throws(() => createTheme({ brand: '#0026EA', accent: 'rgb(0,0,0)' }), /accent must be a hex colour/);
  assert.throws(() => createTheme({ brand: '#0026EA', neutral: '' }), /neutral must be a hex colour/);
  assert.throws(() => createTheme({ brand: '#0026EA', overrides: { 'color-link': 'red' } }), /overrides must map custom property names/);
});

test('neutral produces all 21 steps on the base scale\'s own lightness, tinted toward the hue', () => {
  const result = createTheme({ brand: '#0026EA', neutral: '#78716c' });
  assert.equal(BASE_STEPS.length, 21);
  for (const half of [75, 150, 250, 350, 450, 550, 650, 750, 850, 925]) assert.ok(BASE_STEPS.includes(half));

  for (const step of BASE_STEPS) {
    const hex = result.tokens[`--zabi-base-${step}`];
    assert.match(hex, /^#[0-9a-f]{6}$/, `--zabi-base-${step}`);
    const expected = measureLightness(defaults.light[`--zabi-base-${step}`]);
    assert.ok(Math.abs(measureLightness(hex) - expected) <= 1, `base-${step} is L* ${measureLightness(hex)}, the base scale has ${expected}`);
    // Warm: red at or above blue, where the default zinc greys lean blue.
    const [r, , b] = [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16));
    assert.ok(r >= b, `base-${step} ${hex} is not tinted warm`);
  }
  assert.notEqual(result.tokens['--zabi-base-500'], defaults.light['--zabi-base-500']);
  assert.deepEqual(contrastWarnings(result), []);

  // The whole neutral system follows, dark surfaces included.
  const { light, dark } = themed(result.tokens);
  assert.equal(resolveTokenColor(light, '--color-headline'), result.tokens['--zabi-base-900']);
  assert.equal(resolveTokenColor(dark, '--color-surface-base'), result.tokens['--zabi-base-900']);
  assert.notEqual(resolveTokenColor(dark, '--color-surface-raised'), '#262629');

  // A saturated colour as the neutral is only a hue: it stays a grey, and says so.
  const loud = createTheme({ brand: '#0026EA', neutral: '#C17B00' });
  assert.match(loud.warnings.find((w) => w.option === 'neutral').message, /only its hue is used/);
  const [r, g, b] = [1, 3, 5].map((i) => parseInt(loud.tokens['--zabi-base-500'].slice(i, i + 2), 16));
  assert.ok(Math.max(r, g, b) - Math.min(r, g, b) < 40, 'a neutral step came out saturated');
  assert.deepEqual(contrastWarnings(loud), []);
});

test('accent builds its own ramp and labels, and every pair still passes for both brands', () => {
  for (const brand of BRANDS) {
    const result = createTheme({ brand, accent: '#ff3366', neutral: '#78716c' });
    for (const step of RAMP_STEPS) assert.match(result.tokens[`--zabi-accent-${step}`], /^#[0-9a-f]{6}$/);
    assert.deepEqual(contrastWarnings(result), []);
    const { light, dark } = themed(result.tokens);
    assert.equal(resolveTokenColor(light, '--color-accent'), result.tokens['--zabi-accent-600']);
    assert.equal(resolveTokenColor(dark, '--color-accent'), result.tokens['--zabi-accent-400']);
    assert.equal(resolveTokenColor(dark, '--color-on-accent'), result.tokens['--zabi-accent-950']);
  }
});

test('the bin runs from dist: css on stdout, summary on stderr', () => {
  for (const brand of BRANDS) {
    const result = run('--brand', brand);
    assert.equal(result.status, 0, result.stderr);
    assert.equal(result.stdout, createTheme({ brand }).css);
    assert.match(result.stderr, /every role pair passes WCAG AA in light and dark\./);
    assert.doesNotMatch(result.stderr, /warning:/);
  }
  const full = run('--brand=#0026EA', '--accent', '#ff3366', '--neutral', '#78716c', '--strict');
  assert.equal(full.status, 0, full.stderr);
  assert.equal(full.stdout, createTheme({ brand: '#0026EA', accent: '#ff3366', neutral: '#78716c' }).css);

  const help = run('--help');
  assert.equal(help.status, 0);
  assert.match(help.stdout, /--brand <hex>/);
  assert.match(help.stdout, /--strict/);
});

test('the bin writes --out and keeps stdout empty', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'zabi-theme-'));
  try {
    const target = path.join(dir, 'nested', 'brand.generated.css');
    const result = run('--brand', '#C17B00', '--out', target);
    assert.equal(result.status, 0, result.stderr);
    assert.equal(result.stdout, '');
    assert.equal(fs.readFileSync(target, 'utf8'), createTheme({ brand: '#C17B00' }).css);
    assert.match(result.stderr, /wrote .*brand\.generated\.css \(brand closest to step 500\)/);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test('the bin refuses bad input with a clear message and exit 2', () => {
  const cases = [
    [[], /--brand is required/],
    [['--brand'], /--brand needs a value/],
    [['--brand', 'blue'], /brand must be a hex colour such as "#0026EA" or "#06e" \(got "blue"\)/],
    [['--brand', '#0026EA', '--accent', '#zzz'], /accent must be a hex colour/],
    [['--brand', '#0026EA', '--colour', 'x'], /unknown option "--colour"/],
    [['--brand', '#0026EA', 'stray'], /unexpected argument "stray"/],
    [['--brand', '#0026EA', '--set', 'nonsense'], /--set needs <token>=<value>/],
  ];
  for (const [args, message] of cases) {
    const result = run(...args);
    assert.equal(result.status, 2, `${args.join(' ')} exited ${result.status}`);
    assert.match(result.stderr, message);
    assert.equal(result.stdout, '', `${args.join(' ')} printed css`);
  }
});

test('the bin warns on stderr, and --strict turns a failed pair into exit 1', () => {
  const args = ['--brand', '#0026EA', '--set', '--color-link=var(--zabi-brand-400)'];
  const lenient = run(...args);
  assert.equal(lenient.status, 0);
  assert.match(lenient.stderr, /warning: light · link on page: .* needs 4\.5:1/);
  assert.match(lenient.stderr, /6 role pairs below WCAG AA\./);
  assert.match(lenient.stdout, /--color-link: var\(--zabi-brand-400\);/);

  const strict = run(...args, '--strict');
  assert.equal(strict.status, 1);
  assert.equal(strict.stdout, lenient.stdout);

  // An input note is not a failed pair: --strict lets a grey brand through.
  const grey = run('--brand', '#808080', '--strict');
  assert.equal(grey.status, 0);
  assert.match(grey.stderr, /warning: brand #808080 has almost no colour/);
});

/* ---------- pin: the exact brand colour on the primary action ---------- */

/** What a page computes with a pinned theme: the dark rule comes after `:root`. */
function themedPinned(result) {
  return {
    light: { ...defaults.light, ...result.tokens },
    dark: { ...defaults.light, ...defaults.darkOnly, ...result.tokens, ...(result.darkTokens ?? {}) },
  };
}

function ratio(a, b) {
  const lum = (hex) => {
    const [r, g, b2] = [1, 3, 5].map((i) => {
      const v = parseInt(hex.slice(i, i + 2), 16) / 255;
      return v <= 0.04045 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4;
    });
    return 0.2126 * r + 0.7152 * g + 0.0722 * b2;
  };
  const [hi, lo] = [lum(a), lum(b)].sort((x, y) => y - x);
  return (hi + 0.05) / (lo + 0.05);
}

/** Every token a guarded pair reads, so "dark is as it was" can be said of all of them. */
const guardedTokens = [...new Set(buildThemeData().pairs.flatMap((pair) => [pair.bg, pair.fg]))];

test('without pin the output is what it was: no dark rule, no new fields', () => {
  for (const options of [{ brand: '#0026EA' }, { brand: '#C17B00', accent: '#ff3366', neutral: '#78716c' }]) {
    const plain = createTheme(options);
    for (const off of [false, undefined, null, {}, { brand: false }]) {
      assert.deepEqual(createTheme({ ...options, pin: off }), plain);
    }
    assert.deepEqual(Object.keys(plain), ['css', 'tokens', 'warnings', 'closest']);
    assert.ok(!plain.css.includes('.dark'));
    assert.ok(!plain.css.includes('PINNED'));
    assert.equal(plain.css.match(/\{/g).length, 1, 'one rule, :root');
  }
  // The frozen bytes of the unpinned ultramarine theme: the header and the first and last declarations.
  const { css } = createTheme({ brand: '#0026EA' });
  assert.ok(css.includes(' * is not pinned to a step: the exact hex may not appear below.\n'));
  assert.ok(css.endsWith('  --zabi-on-brand-dark: #ffffff;\n}\n'));
});

test('pin puts the exact colour on the light primary action and leaves dark as it was', () => {
  const brand = '#0026ea';
  const plain = createTheme({ brand: '#0026EA' });
  const pinned = createTheme({ brand: '#0026EA', pin: true });
  assert.deepEqual(createTheme({ brand: '#0026EA', pin: { brand: true } }), pinned);
  const { light, dark } = themedPinned(pinned);

  // The ramp is the unpinned ramp: tints, borders and every other role keep their place.
  for (const step of RAMP_STEPS) assert.equal(pinned.tokens[`--zabi-brand-${step}`], plain.tokens[`--zabi-brand-${step}`]);
  assert.deepEqual(pinned.closest, plain.closest);
  assert.equal(resolveTokenColor(light, '--color-action-primary-subtle'), plain.tokens['--zabi-brand-100']);

  // Light: the fill is the colour, to the byte, with a white label at about 8.5:1.
  assert.equal(pinned.tokens['--color-action-primary'], brand);
  assert.equal(resolveTokenColor(light, '--color-action-primary'), brand);
  assert.equal(resolveTokenColor(light, '--color-action-primary-text'), '#ffffff');
  const white = ratio('#ffffff', brand);
  assert.ok(white > 8.4 && white < 8.7, `white on ${brand} is ${white.toFixed(2)}:1`);

  // Hover and pressed are darker steps of the same colour, and still carry the label.
  const [fill, hover, pressed] = ['', '-hover', '-active'].map((suffix) => resolveTokenColor(light, `--color-action-primary${suffix}`));
  assert.ok(measureLightness(hover) < measureLightness(fill) - 5, `${hover} is not darker than ${fill}`);
  assert.ok(measureLightness(pressed) < measureLightness(hover) - 5, `${pressed} is not darker than ${hover}`);
  for (const colour of [hover, pressed]) assert.ok(ratio('#ffffff', colour) >= 4.5);

  // The roles that are the brand colour by design follow it, because they pass.
  assert.equal(resolveTokenColor(light, '--color-focus-ring'), brand);
  assert.equal(resolveTokenColor(light, '--color-nav-menu-focus'), brand);
  assert.equal(resolveTokenColor(light, '--color-link'), brand);
  assert.equal(resolveTokenColor(light, '--color-primary'), brand);
  assert.deepEqual(pinned.pinned.brand.light, { followed: ['focus ring', 'link'], onRamp: [], states: 'darker' });

  // Dark: this blue is 2.08:1 against a dark page, so dark is not pinned, and
  // every guarded token resolves exactly as it does without pin.
  assert.equal(pinned.pinned.brand.dark.pinned, false);
  assert.ok(pinned.pinned.brand.dark.failed.includes('pinned primary fill against the page'));
  const plainDark = themed(plain.tokens).dark;
  for (const token of guardedTokens) {
    assert.equal(resolveTokenColor(dark, token), resolveTokenColor(plainDark, token), `dark ${token}`);
  }
  assert.equal(resolveTokenColor(dark, '--color-action-primary'), plain.tokens['--zabi-brand-600']);
  assert.equal(resolveTokenColor(dark, '--color-link'), plain.tokens['--zabi-brand-300']);
  // The dark rule only remaps roles: no hex, as in the library's own dark block.
  for (const [role, value] of Object.entries(pinned.darkTokens)) {
    assert.match(value, /^var\(--(color|zabi)-brand-\d+\)$/, `${role}: ${value}`);
    assert.ok(role in pinned.tokens, `${role} is restated in dark without being set on :root`);
  }

  assert.deepEqual(contrastWarnings(pinned), []);
  assert.match(pinned.css, / \* PINNED brand #0026ea: in light, the primary action is exactly this colour\./);
  assert.match(pinned.css, / \*   light, also this colour: focus ring, link\n/);
  assert.match(pinned.css, / \*   dark: NOT pinned\./);
  assert.match(pinned.css, /Contrast: all \d+ role pairs pass WCAG AA in light and dark\./);
  assert.equal(createTheme({ brand: '#0026EA', pin: true }).css, pinned.css, 'same options, same bytes');
});

test('a pinned file carries its dark half under every selector the dark theme is published under', () => {
  const { css, tokens, darkTokens } = createTheme({ brand: '#0026EA', pin: true });
  const rules = [];
  postcss.parse(css).walkRules((rule) => {
    const media = rule.parent.type === 'atrule' ? `@${rule.parent.name} ${rule.parent.params} ` : '';
    const declarations = {};
    rule.walkDecls((decl) => (declarations[decl.prop] = decl.value));
    rules.push([media + rule.selectors.map((s) => s.trim()).join(', '), declarations]);
  });
  assert.deepEqual(rules.map(([selector]) => selector), [
    ':root',
    '.dark, [data-theme="dark"]',
    '@media (prefers-color-scheme: dark) [data-theme="auto"]',
  ]);
  assert.deepEqual(rules[0][1], tokens);
  assert.deepEqual(rules[1][1], darkTokens);
  assert.deepEqual(rules[2][1], darkTokens);
  // The selectors come from the build, not from a second copy in the generator.
  const data = buildThemeData();
  assert.deepEqual(data.darkSelectors, { always: '.dark,\n[data-theme="dark"]', auto: '[data-theme="auto"]', media: '(prefers-color-scheme: dark)' });
});

test('a colour that needs a dark label is pinned with one, and its states go lighter', () => {
  const pinned = createTheme({ brand: '#C17B00', pin: true });
  const { light, dark } = themedPinned(pinned);
  assert.equal(resolveTokenColor(light, '--color-action-primary'), '#c17b00');
  // White is 3.44:1 on this amber; the ramp's dark end passes, on the fill and on both states.
  const label = resolveTokenColor(light, '--color-action-primary-text');
  assert.equal(label, pinned.tokens['--zabi-brand-950']);
  const [fill, hover, pressed] = ['', '-hover', '-active'].map((suffix) => resolveTokenColor(light, `--color-action-primary${suffix}`));
  for (const colour of [fill, hover, pressed]) assert.ok(ratio(label, colour) >= 4.5, `${label} on ${colour}`);
  assert.ok(measureLightness(hover) > measureLightness(fill) && measureLightness(pressed) > measureLightness(hover));
  assert.equal(pinned.pinned.brand.light.states, 'lighter');
  // As text on a white card the amber is 3.4:1, so links stay on the ramp. The ring needs 3:1,
  // which the amber reaches on the near-white page (it did not on the old grey one), so it is pinned.
  assert.deepEqual(pinned.pinned.brand.light.onRamp, ['link']);
  assert.equal(resolveTokenColor(light, '--color-link'), pinned.tokens['--zabi-brand-700']);
  assert.equal(resolveTokenColor(light, '--color-focus-ring'), '#c17b00');
  // It passes on a dark page, so dark takes the colour too.
  assert.equal(pinned.pinned.brand.dark.pinned, true);
  assert.equal(resolveTokenColor(dark, '--color-action-primary'), '#c17b00');
  assert.ok(ratio(resolveTokenColor(dark, '--color-action-primary-text'), '#c17b00') >= 4.5);
  // On the near-white page the amber reaches 3:1, so nothing is left to report (on the old
  // grey page it was 2.92:1 and was reported; the next test keeps a colour that still fails).
  assert.deepEqual(contrastWarnings(pinned), []);
});

test('a colour that cannot be a light button is pinned anyway, and every failing pair is a warning', () => {
  const pinned = createTheme({ brand: '#FFE600', pin: true });
  const { light } = themedPinned(pinned);
  assert.equal(resolveTokenColor(light, '--color-action-primary'), '#ffe600');
  assert.equal(resolveTokenColor(light, '--color-action-primary-text'), pinned.tokens['--zabi-brand-950']);
  const failed = contrastWarnings(pinned).map((w) => `${w.mode} ${w.pair}`);
  assert.deepEqual(failed, [
    'light focus offset gap on primary button',
    // A pale yellow fill is not seen against the white page or card, and the
    // progress bar follows the primary, so it is as pale on its track.
    'light primary fill against the page',
    'light primary fill against a card',
    'light progress fill on track',
    'light pinned primary fill against the page',
    'light pinned primary fill against a card',
  ]);
  // No label pair is among them: the dark end reaches 4.5:1 on the yellow.
  assert.ok(!failed.some((pair) => /label|button primary/.test(pair)));
  for (const warning of contrastWarnings(pinned)) assert.ok(pinned.css.includes(warning.message));
  // The ring and links would be invisible in yellow: they stay on the ramp.
  assert.equal(resolveTokenColor(light, '--color-focus-ring'), pinned.tokens['--zabi-brand-600']);
  assert.equal(resolveTokenColor(light, '--color-link'), pinned.tokens['--zabi-brand-700']);
});

test('pin leaves a role the app set itself alone, in both modes', () => {
  const pinned = createTheme({ brand: '#0026EA', pin: true, overrides: { '--color-link': 'var(--color-brand-800)' } });
  assert.equal(pinned.tokens['--color-link'], 'var(--color-brand-800)');
  assert.ok(!('--color-link' in pinned.darkTokens), 'the dark rule would undo the override in dark');
  assert.equal(pinned.tokens['--color-action-primary'], '#0026ea');
  assert.equal(pinned.tokens['--color-link-hover'], pinned.tokens['--color-action-primary-hover']);
});

test('pin.accent pins the solid accent fill; bad pin values are TypeErrors', () => {
  const pinned = createTheme({ brand: '#0026EA', accent: '#B4005A', pin: { brand: true, accent: true } });
  const { light } = themedPinned(pinned);
  assert.equal(resolveTokenColor(light, '--color-accent'), '#b4005a');
  assert.ok(ratio(resolveTokenColor(light, '--color-on-accent'), '#b4005a') >= 4.5);
  assert.equal(resolveTokenColor(light, '--color-action-primary'), '#0026ea');
  assert.deepEqual(Object.keys(pinned.pinned), ['brand', 'accent']);
  assert.match(pinned.css, / \* PINNED accent #b4005a: in light, the solid accent fill is exactly this colour\./);
  // Accent alone.
  const accentOnly = createTheme({ brand: '#0026EA', accent: '#B4005A', pin: { accent: true } });
  assert.equal(accentOnly.tokens['--color-accent'], '#b4005a');
  assert.ok(!('--color-action-primary' in accentOnly.tokens));

  assert.throws(() => createTheme({ brand: '#0026EA', pin: { accent: true } }), /pin\.accent needs an accent colour/);
  assert.throws(() => createTheme({ brand: '#0026EA', pin: 'yes' }), /pin must be true, false or \{ brand, accent \}/);
  assert.throws(() => createTheme({ brand: '#0026EA', pin: { neutral: true } }), /pin has no "neutral"/);
});

test('the bin takes --pin and --pin-accent, says what it pinned, and --strict still fails a failed pair', () => {
  const pinned = run('--brand', '#0026EA', '--pin');
  assert.equal(pinned.status, 0);
  assert.equal(pinned.stdout, createTheme({ brand: '#0026EA', pin: true }).css);
  assert.match(pinned.stderr, /brand #0026ea is pinned in light; dark keeps the ramp, because the colour fails there\./);
  assert.match(pinned.stderr, /every role pair passes WCAG AA in light and dark\./);
  // Without the flag the bin's output is the unpinned file.
  assert.equal(run('--brand', '#0026EA').stdout, createTheme({ brand: '#0026EA' }).css);

  // A lighter amber than #C17B00: that one reaches 3:1 on the near-white page.
  const amber = run('--brand', '#D08A00', '--pin');
  assert.equal(amber.status, 0);
  assert.match(amber.stderr, /warning: light · pinned primary fill against the page: #d08a00 on #fafafa is 2\.75:1, needs 3:1/);
  assert.match(amber.stderr, /brand #d08a00 is pinned in light and in dark\./);
  assert.equal(run('--brand', '#D08A00', '--pin', '--strict').status, 1);
  assert.equal(run('--brand', '#0026EA', '--pin', '--strict').status, 0);

  const both = run('--brand', '#0026EA', '--accent', '#B4005A', '--pin', '--pin-accent');
  assert.equal(both.stdout, createTheme({ brand: '#0026EA', accent: '#B4005A', pin: { brand: true, accent: true } }).css);

  for (const [args, message] of [
    [['--brand', '#0026EA', '--pin=yes'], /--pin takes no value/],
    [['--brand', '#0026EA', '--pin-accent'], /pin\.accent needs an accent colour/],
  ]) {
    const result = run(...args);
    assert.equal(result.status, 2, args.join(' '));
    assert.match(result.stderr, message);
    assert.equal(result.stdout, '');
  }
  assert.match(run('--help').stdout, /--pin {13}Put the exact brand colour on primary buttons/);
});

/* ---------- a light accent: the label on Button variant="accent" ---------- */

test('a yellow accent gets a label that can be read on it, unpinned and pinned', () => {
  // Unpinned, the accent fill is step 600 of the yellow's ramp, a dark olive: white passes.
  const ramp = createTheme({ brand: '#0026EA', accent: '#FDD715' });
  const onRamp = themed(ramp.tokens).light;
  assert.equal(resolveTokenColor(onRamp, '--color-accent'), ramp.tokens['--zabi-accent-600']);
  assert.equal(resolveTokenColor(onRamp, '--color-on-accent'), '#ffffff');
  assert.ok(ratio('#ffffff', ramp.tokens['--zabi-accent-600']) >= 4.5);
  assert.deepEqual(contrastWarnings(ramp), []);

  // Pinned, the fill is the yellow itself, and white on it is about 1.4:1.
  const pinned = createTheme({ brand: '#0026EA', accent: '#FDD715', pin: { brand: true, accent: true } });
  const { light, dark } = themedPinned(pinned);
  for (const map of [light, dark]) {
    const fills = ['', '-hover', '-active'].map((suffix) => resolveTokenColor(map, `--color-accent${suffix}`));
    const label = resolveTokenColor(map, '--color-on-accent');
    assert.equal(fills[0], '#fdd715');
    assert.equal(label, pinned.tokens['--zabi-accent-950']);
    for (const fill of fills) assert.ok(ratio(label, fill) >= 4.5, `${label} on ${fill}`);
  }
  // What a yellow cannot do on a light surface is said, and nothing about its label is.
  assert.deepEqual(contrastWarnings(pinned).map((w) => `${w.mode} ${w.pair}`), [
    'light pinned accent fill against the page',
    'light pinned accent fill against a card',
  ]);
  // Focused, an accent button is ringed in the brand: 6:1 against the yellow, so the white gap is not needed.
  assert.ok(ratio(resolveTokenColor(light, '--color-focus-ring'), '#fdd715') >= 3);
  assert.ok(ratio(resolveTokenColor(light, '--color-focus-ring-offset'), '#fdd715') < 3);
  // The outline of an accent Rating star is the accent's text step, which stays on the ramp.
  assert.equal(resolveTokenColor(light, '--color-accent-text'), pinned.tokens['--zabi-accent-700']);
  for (const surface of ['--color-surface-base', '--color-surface-raised', '--color-surface-inset']) {
    for (const map of [light, dark]) {
      assert.ok(ratio(resolveTokenColor(map, '--color-accent-text'), resolveTokenColor(map, surface)) >= 3, surface);
    }
  }
});

test('a pair with a second foreground passes on either, and fails when both fail', () => {
  const data = buildThemeData();
  const either = data.pairs.filter((pair) => pair.orFg);
  assert.deepEqual(either.map((pair) => pair.name), ['focus ring or its offset gap on an accent button']);
  // Both fail: an accent pinned to white-ish yellow with the ring forced to the same yellow.
  const both = createTheme({
    brand: '#0026EA',
    accent: '#FDD715',
    pin: { accent: true },
    overrides: { '--color-focus': '#fdd715', '--color-focus-ring-offset': '#fff8c4' },
  });
  assert.ok(contrastWarnings(both).some((w) => w.mode === 'light' && w.pair === 'focus ring or its offset gap on an accent button'));
});

/* ---------- neutralChroma ---------- */

const { toOklch } = await import(pathToFileURL(path.join(distDir, 'lib', 'ramp-math.js')).href);
const INK_ROLES = [
  '--color-action-secondary',
  '--color-action-secondary-hover',
  '--color-action-secondary-active',
  '--color-surface-hover',
  '--color-surface-active',
  '--color-border-overlay',
];

test('without neutralChroma nothing about the ink roles or the dark rules appears', () => {
  for (const options of [{ brand: '#0026EA' }, { brand: '#0026EA', neutral: '#0026EA' }]) {
    const plain = createTheme(options);
    assert.ok(!plain.css.includes('color-mix'));
    assert.ok(!plain.css.includes('.dark'));
    assert.ok(!('darkTokens' in plain));
    for (const role of [...INK_ROLES, '--shadow-color']) assert.ok(!(role in plain.tokens), role);
    // Null and undefined are "not given".
    assert.equal(createTheme({ ...options, neutralChroma: undefined }).css, plain.css);
    assert.equal(createTheme({ ...options, neutralChroma: null }).css, plain.css);
  }
  // The neutral ramp is still capped at 0.03: the saturated input only gives its hue.
  const capped = createTheme({ brand: '#0026EA', neutral: '#0026EA' });
  assert.ok(toOklch(capped.tokens['--zabi-base-500']).c <= 0.031);
  assert.ok(capped.warnings.some((w) => w.option === 'neutral' && /saturated/.test(w.message)));
});

test('neutralChroma lifts the cap: the ramp keeps its hue and reaches the asked chroma', () => {
  const capped = createTheme({ brand: '#0026EA', neutral: '#607296' });
  const tinted = createTheme({ brand: '#0026EA', neutral: '#607296', neutralChroma: 0.05 });
  const mid = toOklch(tinted.tokens['--zabi-base-500']);
  assert.ok(mid.c > 0.045 && mid.c < 0.055, `base-500 chroma ${mid.c}`);
  assert.ok(Math.abs(mid.h - toOklch('#607296').h) < 3, `base-500 hue ${mid.h}`);
  assert.ok(toOklch(capped.tokens['--zabi-base-500']).c < 0.03);
  // Same 21 steps, same lightness: only the chroma moves.
  for (const step of BASE_STEPS) {
    const token = `--zabi-base-${step}`;
    assert.ok(token in tinted.tokens, token);
    assert.ok(Math.abs(measureLightness(tinted.tokens[token]) - measureLightness(capped.tokens[token])) < 1, token);
  }
  // No saturated-colour note when the author chose the chroma.
  const saturated = createTheme({ brand: '#0026EA', neutral: '#0026EA', neutralChroma: 0.05 });
  assert.ok(!saturated.warnings.some((w) => w.option === 'neutral'));
  // The contrast check runs on what is emitted.
  assert.deepEqual(contrastWarnings(tinted), []);
  assert.match(tinted.css, /all \d+ role pairs pass WCAG AA/);
});

test('with neutralChroma the ink roles are mixes of the neutral ramp, and dark says its own', () => {
  const result = createTheme({ brand: '#0026EA', neutral: '#607296', neutralChroma: 0.05 });
  const alphas = { '--color-action-secondary': 10, '--color-action-secondary-hover': 15, '--color-action-secondary-active': 20, '--color-surface-hover': 9, '--color-surface-active': 15, '--color-border-overlay': 10 };
  for (const [role, percent] of Object.entries(alphas)) {
    assert.equal(result.tokens[role], `color-mix(in srgb, var(--zabi-base-900) ${percent}%, transparent)`, role);
  }
  const darkAlphas = { '--color-action-secondary': 9, '--color-action-secondary-hover': 15, '--color-action-secondary-active': 21, '--color-surface-hover': 8, '--color-surface-active': 14 };
  for (const [role, percent] of Object.entries(darkAlphas)) {
    assert.equal(result.darkTokens[role], `color-mix(in srgb, var(--zabi-base-50) ${percent}%, transparent)`, role);
  }
  // Dark's overlay edge is a ramp step already; the light mix must not reach it.
  assert.equal(result.darkTokens['--color-border-overlay'], defaults.darkOnly['--color-border-overlay']);
  // The shadow is the triplet of step 900 in light and stays black in dark.
  const hex = result.tokens['--zabi-base-900'];
  assert.equal(result.tokens['--shadow-color'], [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16)).join(' '));
  assert.equal(result.darkTokens['--shadow-color'], '0 0 0');
  // The modal scrim is not touched.
  assert.ok(!('--color-overlay' in result.tokens) && !('--color-overlay' in result.darkTokens));
  assert.ok(!('pinned' in result));
  // The file carries the dark half under every selector the dark theme is published under.
  const root = postcss.parse(result.css);
  const rules = [];
  root.walkRules((rule) => rules.push(rule.selector));
  assert.deepEqual(rules, [':root', '.dark,\n[data-theme="dark"]', '[data-theme="auto"]']);
  const dark = {};
  root.walkRules('.dark,\n[data-theme="dark"]', (rule) => rule.walkDecls((d) => { dark[d.prop] = d.value; }));
  assert.deepEqual(dark, result.darkTokens);
  // Deterministic.
  assert.equal(createTheme({ brand: '#0026EA', neutral: '#607296', neutralChroma: 0.05 }).css, result.css);
});

test('a role the app overrides is not replaced by an ink role, in either mode', () => {
  const result = createTheme({
    brand: '#0026EA', neutral: '#607296', neutralChroma: 0.05,
    overrides: { '--color-surface-hover': 'rgba(0, 0, 0, 0.05)', '--shadow-color': '1 2 3' },
  });
  assert.equal(result.tokens['--color-surface-hover'], 'rgba(0, 0, 0, 0.05)');
  assert.equal(result.tokens['--shadow-color'], '1 2 3');
  assert.ok(!('--color-surface-hover' in result.darkTokens));
  assert.ok(!('--shadow-color' in result.darkTokens));
});

test('an ink role overridden in one mode keeps the ramp ink in the other (Z-061)', () => {
  const base = { brand: '#0026EA', neutral: '#607296', neutralChroma: 0.05 };
  const plain = createTheme(base);
  const tintedDark = 'color-mix(in srgb, var(--zabi-base-50) 9%, transparent)';
  assert.equal(plain.darkTokens['--color-action-secondary'], tintedDark);

  // Light only: dark is the tinted mix, not the library's rgba(250, 250, 250, 0.09).
  const lightOnly = createTheme({ ...base, overrides: { light: { '--color-action-secondary': '#dde6ff', '--shadow-color': '1 2 3' } } });
  assert.equal(lightOnly.tokens['--color-action-secondary'], '#dde6ff');
  assert.equal(lightOnly.darkTokens['--color-action-secondary'], tintedDark);
  assert.equal(lightOnly.tokens['--shadow-color'], '1 2 3');
  assert.equal(lightOnly.darkTokens['--shadow-color'], plain.darkTokens['--shadow-color']);
  // The roles it did not name are what they are without the override.
  assert.equal(lightOnly.darkTokens['--color-action-secondary-hover'], plain.darkTokens['--color-action-secondary-hover']);
  assert.equal(lightOnly.tokens['--color-action-secondary-hover'], plain.tokens['--color-action-secondary-hover']);

  // Dark only: light keeps the ramp ink.
  const darkOnly = createTheme({ ...base, overrides: { dark: { '--color-action-secondary': '#222233' } } });
  assert.equal(darkOnly.tokens['--color-action-secondary'], plain.tokens['--color-action-secondary']);
  assert.equal(darkOnly.darkTokens['--color-action-secondary'], '#222233');
});

test('neutralChroma works together with pin and keeps the dark half of both', () => {
  const result = createTheme({ brand: '#0026EA', neutral: '#607296', neutralChroma: 0.05, pin: true });
  assert.ok(result.pinned.brand);
  assert.ok(result.darkTokens['--color-surface-hover'].includes('--zabi-base-50'));
  assert.ok('--color-action-primary' in result.darkTokens);
  assert.ok(result.css.includes('PINNED brand'));
});

test('neutralChroma is validated', () => {
  const base = { brand: '#0026EA', neutral: '#607296' };
  for (const bad of [-0.01, 0.11, NaN, Infinity, '0.05', {}, true]) {
    assert.throws(() => createTheme({ ...base, neutralChroma: bad }), (error) => error instanceof TypeError && /neutralChroma must be a number from 0 to 0\.1/.test(error.message), String(bad));
  }
  assert.throws(() => createTheme({ brand: '#0026EA', neutralChroma: 0.05 }), (error) => error instanceof TypeError && /neutralChroma needs a neutral colour/.test(error.message));
  // The limits themselves are fine, and 0 is a pure grey with ink still following the ramp.
  assert.ok(createTheme({ ...base, neutralChroma: 0.1 }));
  const grey = createTheme({ ...base, neutralChroma: 0 });
  assert.ok(toOklch(grey.tokens['--zabi-base-500']).c < 0.005);
  assert.ok(grey.tokens['--color-surface-hover'].includes('--zabi-base-900'));
});

test('the bin takes --neutral-chroma and refuses a bad one with exit 2', () => {
  const ok = run('--brand', '#0026EA', '--neutral', '#607296', '--neutral-chroma', '0.05');
  assert.equal(ok.status, 0, ok.stderr);
  assert.equal(ok.stdout, createTheme({ brand: '#0026EA', neutral: '#607296', neutralChroma: 0.05 }).css);
  for (const args of [['--neutral', '#607296', '--neutral-chroma', 'abc'], ['--neutral', '#607296', '--neutral-chroma', '0.5'], ['--neutral-chroma', '0.05']]) {
    const bad = run('--brand', '#0026EA', ...args);
    assert.equal(bad.status, 2, args.join(' '));
    assert.equal(bad.stdout, '');
    assert.match(bad.stderr, /neutral-chroma|neutralChroma/);
  }
  assert.match(run('--help').stdout, /--neutral-chroma/);
});

/* ---------- per-mode overrides ---------- */

const sha = (text) => crypto.createHash('sha256').update(text).digest('hex');
const darkRule = (css) => css.slice(css.indexOf('.dark,'), css.indexOf('@media'));
const mediaRule = (css) => css.slice(css.indexOf('@media'));
const declarationOf = (block, name) => new RegExp(`${name}: ([^;]+);`).exec(block)?.[1];

test('without light or dark overrides the bytes are what they were before the option existed', () => {
  // Hashes of the css from the generator before per-mode overrides. The header
  // counts the contrast pairs, so they move when a pair is added (188 to 192 to 193 to 195, then the segment thumb pairs; the flat hash moved when the pressed field became a mix of the field:
  // the field edge on the field fill, the page and the card, then the progress fill on its track, each in both modes).
  // They moved again for 9a: the generator now resolves the control veil pairs (the strengths are in its data) and the tonal, outline and toggle pairs were added, so the header counts 260; the bar pairs (active tab pill, on-brand bar, headline on a bar) moved the header and the bytes again, and so did the chrome token and the bar tokens; and the pinned amber's veil is flipped to lighten-only (its label is dark).
  // Then for Z-043: the dark primary and danger are the light steps with a white label (the dark label knob is white, the header counts 4 more pairs: the primary and danger fills against the page and the card).
  // Then for 16a (Z-044): the field edge is guarded on the elevated surface and the overlay (two pairs per mode, so the header counts 4 more), and the dark surfaces, hairline, rim and shadows moved.
  const before = {
    plain: [{ brand: '#0026EA' }, 'c51e89d11bba1058f8f3b7b341bb58668c7bcfed60e95c0fd5e3d72a339e8a25'],
    flat: [
      { brand: '#0026EA', overrides: { '--color-surface-raised': '#f8faff', '--color-link': 'var(--color-brand-800)' } },
      'd95354405f3916816e0ee5f47cb6dcca046131cbfd73424591005f2f4d778533',
    ],
    pinned: [
      { brand: '#C17B00', accent: '#ff3366', pin: true, overrides: { '--color-link': 'var(--color-brand-800)' } },
      '1159408929767ec07f0a1169dacf85133123041e60fc81ed41bdcce33fba777e',
    ],
    neutral: [
      { brand: '#0026EA', neutral: '#607296', neutralChroma: 0.05, pin: { brand: true }, overrides: { '--shadow-color': '1 2 3' } },
      'cc4ed626282444074c986a145ea98df7090fc1bf005e1e7847633566aecb547f',
    ],
  };
  for (const [name, [options, hash]] of Object.entries(before)) {
    assert.equal(sha(createTheme(options).css), hash, name);
  }
  // `both` is the flat form, and empty mode maps write nothing.
  const flat = { '--color-surface-raised': '#f8faff', '--color-link': 'var(--color-brand-800)' };
  const css = createTheme({ brand: '#0026EA', overrides: flat }).css;
  assert.equal(createTheme({ brand: '#0026EA', overrides: { both: flat } }).css, css);
  assert.equal(createTheme({ brand: '#0026EA', overrides: { ...flat, light: {}, dark: {} } }).css, css);
  assert.equal(createTheme({ brand: '#0026EA', overrides: { both: flat } }).darkTokens, undefined);
});

test('a light override stays in light: :root has it and every dark block restates the library dark value', () => {
  const tinted = { '--color-surface-raised': '#f8faff', '--color-surface-overlay': '#f8faff' };
  const result = createTheme({ brand: '#0026EA', overrides: { light: tinted } });
  assert.equal(result.tokens['--color-surface-raised'], '#f8faff');
  assert.equal(result.tokens['--color-surface-overlay'], '#f8faff');
  for (const name of Object.keys(tinted)) {
    assert.equal(result.darkTokens[name], defaults.darkOnly[name]);
    assert.notEqual(result.darkTokens[name], '#f8faff');
  }
  const root = result.css.slice(0, result.css.indexOf('.dark,'));
  assert.equal(declarationOf(root, '--color-surface-raised'), '#f8faff');
  for (const block of [darkRule(result.css), mediaRule(result.css)]) {
    for (const name of Object.keys(tinted)) assert.equal(declarationOf(block, name), defaults.darkOnly[name]);
  }
  assert.deepEqual(contrastWarnings(result).filter((w) => w.mode === 'dark'), []);
});

test('a dark override is written only under the dark selectors', () => {
  const result = createTheme({ brand: '#0026EA', overrides: { dark: { '--color-surface-raised': '#101820' } } });
  assert.equal('--color-surface-raised' in result.tokens, false);
  assert.equal(result.darkTokens['--color-surface-raised'], '#101820');
  const root = result.css.slice(0, result.css.indexOf('.dark,'));
  assert.doesNotMatch(root, /--color-surface-raised/);
  assert.equal(declarationOf(darkRule(result.css), '--color-surface-raised'), '#101820');
  assert.equal(declarationOf(mediaRule(result.css), '--color-surface-raised'), '#101820');
});

test('the page and the chrome surface are settable per mode, with dark restated', () => {
  assert.equal(defaults.light['--color-surface-base'], 'var(--color-base-50)');
  // D108: the bar fill is the page colour in both modes.
  assert.equal(defaults.light['--color-surface-chrome'], 'var(--color-surface-base)');
  assert.equal(defaults.darkOnly['--color-surface-chrome'], 'var(--color-surface-base)');
  const lightPage = { '--color-surface-base': 'var(--zabi-base-150)' };
  const result = createTheme({ brand: '#0026EA', overrides: { light: lightPage } });
  const root = result.css.slice(0, result.css.indexOf('.dark,'));
  assert.equal(declarationOf(root, '--color-surface-base'), 'var(--zabi-base-150)');
  for (const block of [darkRule(result.css), mediaRule(result.css)]) {
    assert.equal(declarationOf(block, '--color-surface-base'), defaults.darkOnly['--color-surface-base']);
  }
  const chrome = createTheme({
    brand: '#0026EA',
    overrides: { light: { '--color-surface-chrome': '#f8faff' }, dark: { '--color-surface-chrome': '#101820' } },
  });
  assert.equal(declarationOf(chrome.css.slice(0, chrome.css.indexOf('.dark,')), '--color-surface-chrome'), '#f8faff');
  assert.equal(declarationOf(darkRule(chrome.css), '--color-surface-chrome'), '#101820');
  assert.equal(declarationOf(mediaRule(chrome.css), '--color-surface-chrome'), '#101820');
});

test('the bar tokens (D124) default from existing tokens, are restated in dark, and are settable per mode', () => {
  const defaultsOf = { '--color-bar': 'var(--color-surface-chrome)', '--color-bar-brand': 'var(--color-action-primary)', '--color-tabbar-active': 'var(--color-nav-menu-active)' };
  for (const [name, value] of Object.entries(defaultsOf)) {
    assert.equal(defaults.light[name], value, name);
    assert.equal(defaults.darkOnly[name], value, `${name} in dark`);
  }
  assert.match(defaults.light['--color-bar-border'], /var\(--color-headline\) 10%/);
  assert.equal(defaults.darkOnly['--color-bar-border'], defaults.light['--color-bar-border']);
  const result = createTheme({
    brand: '#0026EA',
    overrides: { '--color-bar-brand': '#0026EA', light: { '--color-bar': '#f8faff', '--color-bar-border': '#cbd5e1' }, dark: { '--color-bar': '#101820', '--color-tabbar-active': '#1b2a3a' } },
  });
  const root = result.css.slice(0, result.css.indexOf('.dark,'));
  assert.equal(declarationOf(root, '--color-bar'), '#f8faff');
  assert.equal(declarationOf(darkRule(result.css), '--color-bar'), '#101820');
  assert.equal(declarationOf(darkRule(result.css), '--color-tabbar-active'), '#1b2a3a');
  assert.equal(declarationOf(darkRule(result.css), '--color-bar-border'), defaults.darkOnly['--color-bar-border']);
  assert.equal(declarationOf(root, '--color-bar-brand'), '#0026EA');
  // A flat override reaches both modes through the cascade: dark does not restate it.
  assert.equal(declarationOf(darkRule(result.css), '--color-bar-brand'), undefined);
});

test('both, flat keys and a mode: the specific mode wins in its mode', () => {
  const result = createTheme({
    brand: '#0026EA',
    overrides: {
      '--color-link': 'var(--color-brand-800)', // flat, counts as both
      both: { '--color-surface-raised': '#f8faff', '--color-surface-overlay': '#f0f4ff' },
      light: { '--color-surface-raised': '#ffffff' },
      dark: { '--color-surface-overlay': '#202830' },
    },
  });
  assert.equal(result.tokens['--color-surface-raised'], '#ffffff'); // light beats both
  assert.equal(result.darkTokens['--color-surface-raised'], '#f8faff'); // dark keeps both
  assert.equal(result.tokens['--color-surface-overlay'], '#f0f4ff'); // both on :root
  assert.equal(result.darkTokens['--color-surface-overlay'], '#202830'); // dark beats both
  assert.equal(result.tokens['--color-link'], 'var(--color-brand-800)');
  assert.equal('--color-link' in (result.darkTokens ?? {}), false);
});

test('the contrast check uses each mode\'s own value of a token', () => {
  // A near-black card would fail every dark-on-light text pair if light saw it, and
  // a white one would fail light text on a dark card: each is only wrong in its own mode.
  const lightOnly = createTheme({ brand: '#0026EA', overrides: { light: { '--color-surface-raised': '#101010' } } });
  const lightWarnings = contrastWarnings(lightOnly);
  assert.ok(lightWarnings.length > 0);
  assert.ok(lightWarnings.every((w) => w.mode === 'light'), 'a light-only card must not warn in dark');
  assert.ok(lightWarnings.some((w) => w.background.token === '--color-surface-raised' && w.background.value === '#101010'));

  const darkOnly = createTheme({ brand: '#0026EA', overrides: { dark: { '--color-surface-raised': '#ffffff' } } });
  const darkWarnings = contrastWarnings(darkOnly);
  assert.ok(darkWarnings.length > 0);
  assert.ok(darkWarnings.every((w) => w.mode === 'dark'), 'a dark-only card must not warn in light');

  // The same value in both modes reports where it fails, as before.
  const both = createTheme({ brand: '#0026EA', overrides: { both: { '--color-surface-raised': '#101010' } } });
  assert.ok(contrastWarnings(both).some((w) => w.mode === 'light'));
});

test('per-mode overrides take part in the "on" colours and leave pin and the ink roles alone', () => {
  // The app sets the primary fill in light only: pin does not write it, in either mode.
  const pinned = createTheme({ brand: '#0026EA', pin: true, overrides: { light: { '--color-action-primary': '#123456' } } });
  assert.equal(pinned.tokens['--color-action-primary'], '#123456');
  assert.equal(pinned.darkTokens['--color-action-primary'], defaults.darkOnly['--color-action-primary'] ?? defaults.light['--color-action-primary']);
  // An ink role set in dark only is not replaced by the neutral-chroma ink in dark.
  const ink = createTheme({
    brand: '#0026EA', neutral: '#607296', neutralChroma: 0.05,
    overrides: { dark: { '--color-surface-hover': 'rgba(255, 255, 255, 0.2)' } },
  });
  assert.equal(ink.darkTokens['--color-surface-hover'], 'rgba(255, 255, 255, 0.2)');
  // Light, which it did not name, keeps the ramp's ink (Z-061; until 9.0 it fell back to the library's grey).
  assert.equal(ink.tokens['--color-surface-hover'], createTheme({ brand: '#0026EA', neutral: '#607296', neutralChroma: 0.05 }).tokens['--color-surface-hover']);
});

test('an overridden ramp token restates the ramp the file writes, not the library default', () => {
  const result = createTheme({ brand: '#0026EA', overrides: { light: { '--zabi-brand-600': '#112233' } } });
  assert.equal(result.tokens['--zabi-brand-600'], '#112233');
  assert.match(result.darkTokens['--zabi-brand-600'], /^#[0-9a-f]{6}$/);
  assert.notEqual(result.darkTokens['--zabi-brand-600'], '#112233');
  assert.equal(result.darkTokens['--zabi-brand-600'], createTheme({ brand: '#0026EA' }).tokens['--zabi-brand-600']);
});

test('per-mode overrides are validated, and the errors name the key path', () => {
  const bad = (overrides) => () => createTheme({ brand: '#0026EA', overrides });
  assert.throws(bad({ light: 'red' }), /overrides\.light must be an object/);
  assert.throws(bad({ dark: null }), /overrides\.dark must be an object/);
  assert.throws(bad({ both: ['x'] }), /overrides\.both must be an object/);
  assert.throws(bad({ light: { 'color-link': 'red' } }), /overrides\.light\["color-link"\]/);
  assert.throws(bad({ dark: { '--color-link': '' } }), /overrides\.dark\["--color-link"\]/);
  assert.throws(bad({ both: { '--color-link': 4 } }), /overrides\.both\["--color-link"\].*got --color-link: 4/);
  assert.throws(bad({ light: {}, link: 'red' }), /overrides has no "link"/);
  assert.throws(bad({ light: {}, '--color-link': '  ' }), /overrides\["--color-link"\]/);
  // The flat form keeps its message.
  assert.throws(bad({ 'color-link': 'red' }), /overrides must map custom property names/);
});

test('the bin takes --set-light and --set-dark, and --set alone is still the flat form', () => {
  const light = run('--brand', '#0026EA', '--set-light', '--color-surface-raised=#f8faff', '--set-light=--color-surface-overlay=#f8faff');
  assert.equal(light.status, 0, light.stderr);
  assert.equal(
    light.stdout,
    createTheme({ brand: '#0026EA', overrides: { light: { '--color-surface-raised': '#f8faff', '--color-surface-overlay': '#f8faff' } } }).css,
  );
  assert.match(light.stdout, /\.dark,\n\[data-theme="dark"\] \{\n {2}--color-surface-raised: var\(--zabi-base-850\)/);

  const mixed = run('--brand', '#0026EA', '--set', '--color-link=var(--color-brand-800)', '--set-dark', '--color-surface-raised=#101820');
  assert.equal(mixed.status, 0, mixed.stderr);
  assert.equal(
    mixed.stdout,
    createTheme({ brand: '#0026EA', overrides: { both: { '--color-link': 'var(--color-brand-800)' }, dark: { '--color-surface-raised': '#101820' } } }).css,
  );

  const flat = run('--brand', '#0026EA', '--set', '--color-link=var(--color-brand-800)');
  assert.equal(flat.stdout, createTheme({ brand: '#0026EA', overrides: { '--color-link': 'var(--color-brand-800)' } }).css);

  for (const flag of ['--set-light', '--set-dark']) {
    const badUse = run('--brand', '#0026EA', flag, 'nonsense');
    assert.equal(badUse.status, 2);
    assert.match(badUse.stderr, new RegExp(`${flag} needs <token>=<value>`));
  }
  const help = run('--help').stdout;
  assert.match(help, /--set-light <t>=<v>/);
  assert.match(help, /--set-dark <t>=<v>/);
});

test('the field edge is a guarded foreground: 3:1 on the field fill, the page, the card, the elevated surface and the overlay', async () => {
  const { buildPairs } = await import('../scripts/contrast-pairs.js');
  const pairs = buildPairs().filter((p) => p.fg === '--color-input-border' && !p.behind);
  assert.deepEqual(
    pairs.map((p) => [p.bg, p.min]).sort(),
    [['--color-background', 3], ['--color-input', 3], ['--color-surface-elevated', 3], ['--color-surface-overlay', 3], ['--color-surface-raised', 3]],
  );
  // The generator ships the same list, so a consumer's theme is checked too.
  const shipped = JSON.parse(JSON.stringify(buildThemeData().pairs)).filter((p) => p.fg === '--color-input-border' && !p.behind);
  assert.equal(shipped.length, 5);
});

/* ---------- materials (D97) ---------- */

const MATERIAL_FILL = (percent) => `color-mix(in srgb, var(--color-surface-chrome) ${percent}%, transparent)`;
const materialWarnings = (result, level) => contrastWarnings(result).filter((w) => w.pair.startsWith(`material ${level} `));

test('the library meets its own material floors, and a material one step below fails the guard', () => {
  const css = fs.readFileSync(path.join(projectRoot, 'src', 'app.css'), 'utf8');
  const guard = (source) => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'zabi-materials-'));
    const file = path.join(dir, 'app.css');
    fs.writeFileSync(file, source);
    return spawnSync(process.execPath, [path.join(projectRoot, 'scripts', 'check-contrast.js'), file], { encoding: 'utf8' });
  };
  assert.equal(guard(css).status, 0, 'the shipped alphas must pass');
  // The floors against the page-colour chrome: light 82% (focus ring over the
  // worst backdrop), dark 72%; shipped with a step or two of margin. One step
  // (2%) below the floor fails.
  assert.ok(css.includes('--material-alpha-regular: 84%;') && css.includes('--material-alpha-regular: 76%;'));
  const light = guard(css.replace('--material-alpha-regular: 84%;', '--material-alpha-regular: 80%;'));
  assert.equal(light.status, 1);
  assert.match(light.stderr, /light · material regular · .* over the worst backdrop/);
  const dark = guard(css.replace('--material-alpha-regular: 76%;', '--material-alpha-regular: 70%;'));
  assert.equal(dark.status, 1);
  assert.match(dark.stderr, /dark · material regular · .* over the worst backdrop/);
  // Thick carries the caption: it fails first on that, in dark. The dark overlay is the
  // elevated tone now (L 27.4, it was L 39), so the floor fell from 96% to 84%: the
  // shipped 98% is conservative until the alphas are re-solved. 80% is under the floor.
  const thick = guard(css.replace('--material-alpha-thick: 98%;', '--material-alpha-thick: 80%;'));
  assert.equal(thick.status, 1);
  assert.match(thick.stderr, /dark · material thick · caption over the worst backdrop/);
});

test('material tokens are overridable per mode with dark restated, and a too-thin fill is reported', () => {
  const data = buildThemeData();
  assert.ok(data.pairs.some((pair) => pair.behind && pair.bg === '--color-material-thick'), 'the material pairs are not in the shared list');
  const ok = createTheme({
    brand: '#0026EA',
    overrides: { light: { '--color-material-regular': MATERIAL_FILL(90) }, dark: { '--color-material-regular': MATERIAL_FILL(92) } },
  });
  assert.equal(ok.tokens['--color-material-regular'], MATERIAL_FILL(90));
  assert.equal(ok.darkTokens['--color-material-regular'], MATERIAL_FILL(92));
  assert.deepEqual(materialWarnings(ok, 'regular'), []);

  // Light only, too thin: reported in light; dark is restated with the library's own value, so it stays clean.
  const thin = createTheme({ brand: '#0026EA', overrides: { light: { '--color-material-regular': MATERIAL_FILL(40) } } });
  assert.equal(thin.tokens['--color-material-regular'], MATERIAL_FILL(40));
  assert.equal(thin.darkTokens['--color-material-regular'], defaults.light['--color-material-regular']);
  const warned = materialWarnings(thin, 'regular');
  assert.ok(warned.length > 0 && warned.every((w) => w.mode === 'light'), JSON.stringify(warned.map((w) => w.message)));
  assert.ok(warned.some((w) => /over the worst backdrop/.test(w.pair)));

  // Dark too thin, and `both`: each mode is read with its own value.
  const both = createTheme({ brand: '#0026EA', overrides: { '--color-material-thin': MATERIAL_FILL(40) } });
  assert.deepEqual([...new Set(materialWarnings(both, 'thin').map((w) => w.mode))].sort(), ['dark', 'light']);

  // The highlight, rim and shadow follow a neutral override.
  const tinted = createTheme({ brand: '#0026EA', neutral: '#607296', neutralChroma: 0.05 });
  assert.deepEqual(contrastWarnings(tinted), []);
  const maps = themed({ ...tinted.tokens });
  assert.match(defaults.light['--color-material-rim'], /var\(--zabi-base-900\)/);
  assert.match(defaults.darkOnly['--color-material-rim'], /var\(--zabi-base-50\)/);
  assert.ok(maps.light['--zabi-base-900'] !== defaults.light['--zabi-base-900']);
});

/* ---------- gradients (D99) ---------- */

test('the gradient worst-case pairs pass as shipped, and one step above the solved strength fails the guard', () => {
  const css = fs.readFileSync(path.join(projectRoot, 'src', 'app.css'), 'utf8');
  const guard = (source) => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'zabi-gradients-'));
    const file = path.join(dir, 'app.css');
    fs.writeFileSync(file, source);
    return spawnSync(process.execPath, [path.join(projectRoot, 'scripts', 'check-contrast.js'), file], { encoding: 'utf8' });
  };
  assert.equal(guard(css).status, 0, 'the shipped strengths must pass');
  assert.ok(css.includes('--gradient-canvas-strength: 55%;') && css.includes('--gradient-canvas-strength: 25%;'));
  const light = guard(css.replace('--gradient-canvas-strength: 55%;', '--gradient-canvas-strength: 60%;'));
  assert.equal(light.status, 1);
  assert.match(light.stderr, /light · canvas wash (brand|accent) · /);
  const dark = guard(css.replace('--gradient-canvas-strength: 25%;', '--gradient-canvas-strength: 30%;'));
  assert.equal(dark.status, 1);
  assert.match(dark.stderr, /dark · canvas wash (brand|accent) · field edge/);
  // Light is darken-only: a lightened top takes the white label under 4.5:1.
  assert.ok(css.includes('--gradient-control-top-strength: 0%;') && css.includes('--gradient-control-bottom-strength: 14%;'));
  const veil = guard(css.replace('--gradient-control-top-strength: 0%;', '--gradient-control-top-strength: 10%;'));
  assert.equal(veil.status, 1);
  assert.match(veil.stderr, /light · (primary|accent|danger) gradient top · /);
});

test('gradient tokens follow a rebrand and are overridable per mode with dark restated', () => {
  const brandOnly = createTheme({ brand: '#0026EA' });
  const rebrand = createTheme({ brand: '#B4231C', accent: '#0F766E' });
  const resolved = (r) => themed({ ...r.tokens });
  // The wash reads the brand and accent ramps, which a rebrand regenerates.
  assert.match(resolved(rebrand).light['--color-canvas-wash-brand'], /--color-brand-300/);
  assert.match(resolved(rebrand).light['--color-canvas-wash-accent'], /--color-accent-300/);
  assert.notEqual(brandOnly.tokens['--zabi-brand-300'], rebrand.tokens['--zabi-brand-300']);
  assert.notEqual(brandOnly.tokens['--zabi-accent-300'], rebrand.tokens['--zabi-accent-300']);
  assert.ok(buildThemeData().pairs.some((p) => p.behind && p.bg === '--color-canvas-wash-brand'));
  const gradientWarnings = (r) => contrastWarnings(r).filter((w) => /canvas wash|gradient (top|bottom)/.test(w.pair));
  assert.deepEqual(gradientWarnings(rebrand), []);

  const set = createTheme({
    brand: '#0026EA',
    overrides: { light: { '--gradient-canvas-strength': '95%' }, dark: { '--gradient-canvas-strength': '40%' } },
  });
  assert.equal(set.tokens['--gradient-canvas-strength'], '95%');
  assert.equal(set.darkTokens['--gradient-canvas-strength'], '40%');
  assert.ok(gradientWarnings(set).some((w) => w.mode === 'light' && /canvas wash/.test(w.pair)));
});

test('a light card override does not break the pressed field: the pressed colour follows the field', () => {
  // Z-040: with the card at #f8faff the pressed field was a fixed base-200,
  // 1.21:1 against it, below the 1.25 the generator holds.
  const result = createTheme({
    brand: '#0026EA',
    neutral: '#607296',
    neutralChroma: 0.08,
    overrides: { light: { '--color-surface-raised': '#f8faff' } },
  });
  const pressed = contrastWarnings(result).filter((w) => /pressed field/.test(w.pair));
  assert.deepEqual(pressed.map((w) => `${w.mode} ${w.pair}`), []);
  // The pressed colour is derived, in both modes, not a ramp step.
  assert.match(defaults.light['--color-input-active'], /^color-mix\(/);
  assert.match(defaults.darkOnly['--color-input-active'], /^color-mix\(/);
});

/* ---------- 9a: control gradients, link follow, button and toggle tokens ---------- */

test('the default call emits no gradient strengths and no link role', () => {
  const result = createTheme({ brand: '#0026EA' });
  for (const name of Object.keys(result.tokens)) {
    assert.ok(!/^--gradient-control-/.test(name) && name !== '--color-link', name);
  }
  assert.equal(result.darkTokens, undefined);
  // The veil pairs are checked by the generator now (the strengths are in its data),
  // for primary, accent and danger, and all pass.
  const veil = buildThemeData().pairs.filter((pair) => pair.gradient);
  assert.deepEqual([...new Set(veil.map((pair) => pair.gradient))].sort(), ['accent', 'danger', 'primary']);
  assert.deepEqual(contrastWarnings(result), []);
});

test('an accent with a dark label gets a lighten-only veil, not a warning', () => {
  // A light pink fill with a navy label (5.9, 5.1 and 4.7:1): darkening the bottom
  // by 14% takes the label under 4.5:1 on hover and pressed.
  const accent = { '--color-accent': '#E27AA6', '--color-accent-hover': '#D96C9B', '--color-accent-active': '#D4639A', '--color-on-accent': '#0B1B4D' };
  const result = createTheme({ brand: '#0026EA', overrides: accent });
  const veil = (r) => r.warnings.filter((w) => / gradient /.test(w.pair));
  assert.deepEqual(veil(result), []);
  assert.equal(result.tokens['--gradient-control-accent-top-strength'], '14%');
  assert.equal(result.tokens['--gradient-control-accent-bottom-strength'], '0%');
  // Primary and danger keep the shared veil.
  assert.ok(!('--gradient-control-top-strength' in result.tokens));
  // Light was flipped, so dark says its own: here it fails too and flips as well.
  assert.ok('--gradient-control-accent-top-strength' in result.darkTokens);
  assert.ok('--gradient-control-accent-bottom-strength' in result.darkTokens);
  // The flipped veil is what a page computes.
  const page = themed({ ...result.tokens });
  assert.match(resolveTokenValue(page.light, '--gradient-control-accent-top-strength'), /^14%$/);

  // An explicit strength wins and is only warned about.
  const explicit = createTheme({
    brand: '#0026EA',
    overrides: { ...accent, '--gradient-control-accent-top-strength': '0%', '--gradient-control-accent-bottom-strength': '14%' },
  });
  assert.equal(explicit.tokens['--gradient-control-accent-bottom-strength'], '14%');
  assert.ok(veil(explicit).some((w) => w.mode === 'light' && /accent gradient bottom/.test(w.pair)));
});

test('a fill no veil can save gets no veil rather than a failing one', () => {
  // The pressed fill alone is 4.39:1 under its label: every strength fails.
  const result = createTheme({
    brand: '#0026EA',
    overrides: { '--color-accent': '#E27AA6', '--color-accent-hover': '#D96C9B', '--color-accent-active': '#CF5C94', '--color-on-accent': '#0B1B4D' },
  });
  assert.equal(result.tokens['--gradient-control-accent-top-strength'], '0%');
  assert.equal(result.tokens['--gradient-control-accent-bottom-strength'], '0%');
  assert.ok(result.warnings.some((w) => w.pair === 'accent fill :active'));
});

test('--color-link follows an overridden primary where every guarded pair still passes', () => {
  const primary = {
    '--color-action-primary': 'var(--color-brand-800)',
    '--color-action-primary-hover': 'var(--color-brand-900)',
    '--color-action-primary-active': 'var(--color-brand-950)',
  };
  const app = createTheme({ brand: '#0026EA', overrides: primary });
  assert.equal(app.tokens['--color-link'], 'var(--color-brand-800)');
  assert.equal(app.tokens['--color-link-hover'], 'var(--color-brand-900)');
  assert.deepEqual(contrastWarnings(app), []);
  // Both modes follow, since the override reaches both.
  assert.equal(app.darkTokens['--color-link'], 'var(--color-brand-800)');

  // Without a hover override only the link moves: the library's hover step is not the app's.
  const noHover = createTheme({ brand: '#0026EA', overrides: { '--color-action-primary': 'var(--color-brand-800)' } });
  assert.equal(noHover.tokens['--color-link'], 'var(--color-brand-800)');
  assert.ok(!('--color-link-hover' in noHover.tokens));

  // Only in the mode the override is set in: a light primary leaves dark's link on the library's.
  const lightOnly = createTheme({ brand: '#0026EA', overrides: { light: primary } });
  assert.equal(lightOnly.tokens['--color-link'], 'var(--color-brand-800)');
  assert.equal(lightOnly.darkTokens['--color-link'], defaults.darkOnly['--color-link'] ?? defaults.light['--color-link']);

  // A primary that fails a link pair (brand-300 as text on the page) leaves the link on the ramp.
  const pale = createTheme({ brand: '#0026EA', overrides: { light: { '--color-action-primary': 'var(--color-brand-300)' } } });
  assert.ok(!('--color-link' in pale.tokens));
  assert.ok(!('--color-link' in (pale.darkTokens ?? {})));

  // An explicit link wins, in the mode it is set in.
  const explicit = createTheme({ brand: '#0026EA', overrides: { ...primary, '--color-link': 'var(--color-brand-700)' } });
  assert.equal(explicit.tokens['--color-link'], 'var(--color-brand-700)');
  assert.ok(!('--color-link-hover' in explicit.tokens));
});

test('the button and toggle tokens exist in both modes and take overrides', () => {
  for (const name of [
    '--color-action-tonal', '--color-action-tonal-hover', '--color-action-tonal-active', '--color-action-tonal-text',
    '--color-action-outline-border', '--color-action-outline-border-hover',
    '--color-toggle-track', '--color-toggle-track-hover', '--color-toggle-track-active', '--color-toggle-track-border',
    '--gradient-control-accent-top-strength', '--gradient-control-accent-bottom-strength',
  ]) {
    assert.ok(name in defaults.light, `light ${name}`);
    assert.ok(name in defaults.darkOnly, `dark ${name}`);
  }
  // Read through a fallback, declared nowhere: setting them is only an override.
  assert.ok(!('--zabi-button-radius' in defaults.light) && !('--zabi-button-font-weight' in defaults.light));
  const result = createTheme({
    brand: '#0026EA',
    overrides: { '--zabi-button-radius': '9999px', light: { '--zabi-button-font-weight': '600' } },
  });
  assert.equal(result.tokens['--zabi-button-radius'], '9999px');
  assert.equal(result.tokens['--zabi-button-font-weight'], '600');
  assert.match(result.css, /--zabi-button-radius: 9999px;/);
  assert.deepEqual(contrastWarnings(result), []);
});

/* ---------- darkPrimary (Z-043): the primary action keeps its hue in dark ---------- */

const flatDarkOverrides = {
  '--zabi-brand-800': '#0026ea',
  '--color-action-primary': 'var(--color-brand-800)',
  '--color-action-primary-hover': 'var(--color-brand-900)',
  '--color-action-primary-active': 'var(--color-brand-950)',
  '--color-accent': '#eb8ffe',
  '--color-accent-hover': 'var(--zabi-accent-300)',
  '--color-accent-active': 'var(--zabi-accent-200)',
  '--zabi-on-accent': '#183a89',
  '--zabi-on-accent-dark': '#183a89',
  '--color-focus': 'var(--color-brand-800)',
  '--color-link-hover': 'var(--color-brand-900)',
  '--color-progress-track': 'var(--color-base-250)',
};
const appInput = { brand: '#0026EA', accent: '#EB8FFE', neutral: '#607296', neutralChroma: 0.08 };

test('darkPrimary "brand" is the default and writes nothing extra; bad values are TypeErrors', () => {
  const plain = createTheme({ brand: '#0026EA' });
  assert.deepEqual(createTheme({ brand: '#0026EA', darkPrimary: 'brand' }), plain);
  assert.deepEqual(createTheme({ brand: '#0026EA', darkPrimary: undefined }), plain);
  assert.equal(plain.darkTokens, undefined);
  assert.ok(!plain.css.includes('.dark'));
  for (const bad of ['Mirror', 'light', true, 1, {}]) {
    assert.throws(() => createTheme({ brand: '#0026EA', darkPrimary: bad }), (error) => error instanceof TypeError && /darkPrimary must be "brand" or "mirror"/.test(error.message), String(bad));
  }
});

test('darkPrimary "mirror" restores the 8.1 dark fills, label and veil, and every pair passes', () => {
  for (const brand of BRANDS) {
    const result = createTheme({ brand, darkPrimary: 'mirror' });
    assert.deepEqual(contrastWarnings(result), [], brand);
    assert.deepEqual(result.darkTokens, {
      '--color-action-primary': 'var(--color-brand-600)',
      '--color-action-primary-hover': 'var(--color-brand-700)',
      '--color-action-primary-active': 'var(--color-brand-800)',
      '--color-action-danger': 'var(--color-error-600)',
      '--color-action-danger-hover': 'var(--color-error-700)',
      '--color-action-danger-active': 'var(--color-error-800)',
      '--color-action-danger-text': 'var(--color-error-50)',
      '--gradient-control-top-strength': '22%',
      '--gradient-control-bottom-strength': '6%',
    });
    // The label is chosen for the pale fill: the ramp's dark end, as in 8.1.
    assert.equal(result.tokens['--zabi-on-brand-dark'], 'var(--zabi-brand-950)');
    const { dark } = themedPinned(result);
    assert.equal(resolveTokenColor(dark, '--color-action-primary'), result.tokens['--zabi-brand-400']);
    assert.equal(resolveTokenColor(dark, '--color-action-primary-text'), result.tokens['--zabi-brand-950']);
    for (const selector of ['.dark,', '[data-theme="auto"]']) assert.ok(result.css.includes(selector));
  }
});

test('darkPrimary "mirror" gives way to an app override of the same role', () => {
  const result = createTheme({ brand: '#0026EA', darkPrimary: 'mirror', overrides: { dark: { '--color-action-primary': 'var(--color-brand-700)' }, both: { '--color-action-danger': 'var(--color-error-700)' } } });
  assert.equal(result.darkTokens['--color-action-primary'], 'var(--color-brand-700)');
  assert.ok(!('--color-action-danger' in result.darkTokens));
  assert.ok(result.darkTokens['--color-action-primary-hover']);
});

test('the dark label tries white first, and keeps the ramp dark end when white fails', () => {
  assert.equal(createTheme({ brand: '#0026EA' }).tokens['--zabi-on-brand-dark'], '#ffffff');
  // An app that moves the dark primary to a pale step (the mirrored steps) keeps a dark label.
  const pale = createTheme({ brand: '#0026EA', overrides: { dark: { '--color-action-primary': 'var(--color-brand-600)', '--color-action-primary-hover': 'var(--color-brand-700)', '--color-action-primary-active': 'var(--color-brand-800)' } } });
  assert.equal(pale.tokens['--zabi-on-brand-dark'], 'var(--zabi-brand-950)');
  assert.deepEqual(contrastWarnings(pale), []);
});

test('darkPrimary with pin: dark takes the pin only where nothing fails, else what it has without pin', () => {
  // This blue fails against the dark page: dark keeps step 600 (or the mirrored step).
  const brand = createTheme({ brand: '#0026EA', pin: true });
  assert.equal(brand.pinned.brand.dark.pinned, false);
  assert.equal(brand.darkTokens['--color-action-primary'], 'var(--zabi-brand-600)');
  assert.equal(brand.darkTokens['--color-action-primary-active'], 'var(--zabi-brand-800)');
  assert.deepEqual(contrastWarnings(brand), []);
  const mirror = createTheme({ brand: '#0026EA', pin: true, darkPrimary: 'mirror' });
  assert.equal(mirror.pinned.brand.dark.pinned, false);
  assert.equal(mirror.darkTokens['--color-action-primary'], 'var(--color-brand-600)');
  assert.equal(mirror.darkTokens['--color-action-danger'], 'var(--color-error-600)');
  assert.deepEqual(contrastWarnings(mirror), []);
  // A mid blue passes in dark: it is pinned there, with darker states as in light.
  const mid = createTheme({ brand: '#2b65ff', pin: true });
  assert.equal(mid.pinned.brand.dark.pinned, true);
  assert.equal(mid.pinned.brand.dark.states, 'darker');
  assert.equal(mid.darkTokens['--color-action-primary'], '#2b65ff');
});

test('an app that sets the primary flat for both modes gets no warnings and keeps its dark primary', () => {
  const result = createTheme({ ...appInput, overrides: flatDarkOverrides });
  assert.deepEqual(result.warnings, []);
  assert.ok(!('--color-action-primary' in result.darkTokens), 'the flat override is left alone in dark');
  const { dark } = themedPinned(result);
  assert.equal(resolveTokenColor(dark, '--color-action-primary'), result.tokens['--zabi-brand-200']);
});

test('the same override under light gives the brand step 600 with a white label in dark', () => {
  const { '--color-action-primary': p, '--color-action-primary-hover': h, '--color-action-primary-active': a, ...rest } = flatDarkOverrides;
  const result = createTheme({ ...appInput, overrides: { both: rest, light: { '--color-action-primary': p, '--color-action-primary-hover': h, '--color-action-primary-active': a } } });
  const { light, dark } = themedPinned(result);
  assert.equal(resolveTokenColor(dark, '--color-action-primary'), '#2b65ff');
  assert.equal(resolveTokenColor(dark, '--color-action-primary-text'), '#ffffff');
  assert.equal(resolveTokenColor(light, '--color-action-primary'), '#0026ea');
  // The app's own track override (base-250 in both modes) is the one pair that
  // fails: the 600 fill is 2.62:1 on it. Reported, not hidden.
  assert.deepEqual(result.warnings.map((w) => `${w.mode} ${w.pair}`), ['dark progress fill on track']);
});

test('the bin takes --dark-primary', () => {
  const args = ['--brand', '#0026EA'];
  assert.equal(run(...args, '--dark-primary', 'brand').stdout, createTheme({ brand: '#0026EA' }).css);
  assert.equal(run(...args, '--dark-primary=mirror').stdout, createTheme({ brand: '#0026EA', darkPrimary: 'mirror' }).css);
  const bad = run(...args, '--dark-primary', 'pale');
  assert.equal(bad.status, 2);
  assert.match(bad.stderr, /darkPrimary must be "brand" or "mirror"/);
});
